### ISSUE TITLE
Unblock Adult Content

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#10]
We have feedback from a user, that they want adult content to be unblocked. If we do this, we need to pay for extra servers. Also, we need to split the build scripts to generate different flavors of the dns adblock.

**Comment by Tomatoide** [comment]
I think there are a lot of other dns servers that provide what this user is looking for which is adblocking only.. but I think what makes bancuh unique is not only effective adblocking but also effective family protection with doh and dot all in simple plug and play no config needed
