### ISSUE TITLE
Add some ad blocking and tracking hosts lists to your blacklists!

### ISSUE THREAD

**Issue by phanluchoa21** [ragibkl/adblock-dns-server#102]
Hi,

Here, I have some adblock and tracking list host file! You can add these host file to your blacklist! (If there is anything in this list that you have added, skip it!)

1.  https://github.com/StevenBlack/hosts
2. https://oisd.nl/
3. https://easylist.to/
4. https://github.com/jerryn70/GoodbyeAds
5. https://github.com/notracking/hosts-blocklists
6. https://github.com/AdAway/adaway.github.io
7. https://kb.adguard.com/general/adguard-ad-filters#tracking-protection-filter
8. https://easylist.to/
9. http://sysctl.org/cameleon
10. https://pgl.yoyo.org/adservers
11. https://someonewhocares.org/hosts
12. http://winhelp2002.mvps.org/hosts.htm
13. https://github.com/EnergizedProtection/block
14. https://github.com/EnergizedProtection/block
15. https://github.com/Yhonay/antipopads
16. https://280blocker.net/
17. https://www.shallalist.de/
18. https://github.com/EnergizedProtection/block
19. https://www.shallalist.de/
20. https://gitlab.com/CHEF-KOCH/cks-filterlist
21. https://github.com/bigdargon/hostsVN
22. https://github.com/privacy-protection-tools/anti-AD
23. https://paulgb.github.io/BarbBlock
24. https://github.com/yous/YousList
25. https://github.com/jdlingyu/ad-wars
26. https://github.com/tomasko126/easylistczechandslovak
27. https://github.com/easylist/EasyListHebrew
28. https://github.com/finnish-easylist-addition/finnish-easylist-addition
29. https://github.com/hufilter/hufilter
30. https://github.com/bkrucarci/turk-adlist
31. https://disconnect.me/
32. https://github.com/lassekongo83/Frellwits-filter-lists
33. https://github.com/CHEF-KOCH/NSABlocklist
34. https://gitlab.com/quidsup/notrack-blocklists
35. https://www.github.developerdan.com/hosts
36. https://unchecky.com/
37. https://fanboy.co.nz/
38. https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html
39. https://badmojr.github.io/1Hosts
40. http://hostsfile.org/hosts.html
41. https://forums.lanik.us/viewforum.php?f=102
42. https://easylist.to/pages/other-supplementary-filter-lists-and-easylist-variants.html
43. https://badmojr.github.io/1Hosts
44. https://notabug.org/latvian-list/adblock-latvian
45. https://github.com/VeleSila/yhosts

And also some of ad youtube links you need to add to blocklists too:

*.fls.doubleclick.net
*.g.doubleclick.net
*.l.doubleclick.net
*.ad.tw.doubleclick.net
*.googlesyndication.com
*.c.googlesyndication.com
*.adservice.google
*.redirector.googlevideo.com
*.pixel.adsafeprotected.com
*.doubleclick.net
*.ad.mo.doubleclick.net
*.manifest.googlevideo.com
*.youtube-nocookie.com
*.securepubads.g.doubleclick.net
*.adservice.google.com
vlxx.to
sextop1.to
sextop1.co
*.raboninco.com
*.advserver.cgv.vn
*.mail-ads.google.com
*.adprotect.net
*.bit.ly
*.bitly.com
*.s0.2mdn.net
*.2mdn.net
*.stats.g.doubleclick.net
*.pagead1.googlesyndication.com
*.pagead.googlesyndication.com
*.serving-sys.com
*.2975c.v.fwmrm.net
*.secure-ds.serving-sys.com
*.s.youtube.com
*.ad.doubleclick.net
*.www.googletagservices.com
*.ad-g.doubleclick.net
*.googleadservices.com
*.static.doubleclick.net
*.ssl.google-analytics.com
*.www-google-analytics.l.google.com
*.pagead.l.doubleclick.net
*.googleadapis.l.google.com
*.pagead2.googlesyndication.com
*.pubads.g.doubleclick.net
*.ads.youtube.com
*.ad.youtube.com
*.googleads4.g.doubleclick.net
*.adf.ly
*.ads.doubleclick.net
*.dts.innovid.com
*.pixel.moatads.com
*.advserver.cgv.vn
*.ads-twitter.com
*.ads.yahoo.com
*.bit.do
*.tiny.cc
*.rebrandly.com
*.shorte.st
*.bl.ink
*.tinyurl.com
*.suggestqueries-clients6.youtube.com
*.ad-stir.com
*.n9.cl
*.adservice.google.com

It's a bit too much but if you add these to your block list then great for the experience!

Thanks!

**Comment by ragibkl** [comment]
@Tomatoide , you've been looking at the blacklist for a while recently. Would you like to take a look at this suggestions as well? I think you can do a better job than me here.

**Comment by Tomatoide** [comment]
@ragibkl Sure, I think I would suggest @phanluchoa21 to take a look at the blacklist: https://github.com/ragibkl/adblock-dns-server/blob/master/data/configuration.yml
Most of these are already included, and the rest are mostly dead projects / outdated / or overly aggressive.
I think the blacklist right now is comprehensive enough and balanced and with the recent changes has less false positives, better user experience
And in regards to youtube ads, dns based blocking can't do much as youtube serves ads through the same domains it serves videos, I would suggest browser based blocking using ublock origin for example, and for apps there is youtube vanced or newpipe

**Comment by phanluchoa21** [comment]
@Tomatoide As you said about youtube ads, how can I block ads by using DNS of Bancuh on computer ? In phone, I can use youtube vanced is ok but in computer how can it ?

**Comment by Tomatoide** [comment]
DNS cannot block youtube ads unfortunately, you can install ublock origin extension on your browser instead:
for firefox: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
for chrome: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by phanluchoa21** [comment]
> DNS cannot block youtube ads unfortunately, you can install ublock origin extension on your browser instead:
> for firefox: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
> for chrome: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

thanks!
