### ISSUE TITLE
Coin blocker lists and family filters

### ISSUE THREAD

**Issue by trimechee** [ragibkl/adblock-dns-server#119]
Hello, I found these awesome and huge no coin filters, it will be amazing if Bancuh dns could add them !

https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html#news

I found also these incredible huge lists collections : 

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist

I previously used ad blocker dns with the anti-porn family filter activated, then I noticed that some youtube videos are blocked, these videos come from my favorite youtube channels which are channels without porno and they are political channels or religious but youtube told me you can't access these videos then I discovered that it's because of the dns which is wrong and classifies political or religious videos as shocking vulgar videos when this is not the case!

there is a filter on youtube that you can easily activate to block shocking content so no need for dns servers with the family option to block youtube content because it can cause errors and the blocking of legitimate videos, I hope that Bancuh dns will make an exception and do not activate the family filter on the youtube site to avoid possible errors and the blocking of legitimate videos!
Thank you very much :)

**Comment by ragibkl** [comment]
> I previously used ad blocker dns with the anti-porn family filter activated, then I noticed that some youtube videos are blocked, these videos come from my favorite youtube channels which are channels without porno and they are political channels or religious but youtube told me you can't access these videos then I discovered that it's because of the dns which is wrong and classifies political or religious videos as shocking vulgar videos when this is not the case!

At the moment, we don't use any family filter on Bancuh DNS for youtube. We only use some rules to enforce safe-search on google, bing, and duckduckgo. You can check the files [here](https://github.com/ragibkl/adblock-dns-server/tree/master/data/overrides.d).  We did have safe-search for youtube in the past, but removed it because it was too strict.

If you found some youtube videos that are blocked, maybe it's not because of Bancuh DNS, but something else instead.

> Hello, I found these awesome and huge no coin filters, it will be amazing if Bancuh dns could add them !
> https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html#news
> I found also these incredible huge lists collections :
> https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist

I think we can try to add them. What do you think @Tomatoide ?

**Comment by Tomatoide** [comment]
I think right now we have a fairly balanced filtering, we don't need to just add more duplicates or risk having false positives.

**Comment by trimechee** [comment]
Great ! thank you so much @ragibkl !

I undersatand @Tomatoide that it could be false positive but here i speak about the dangerous crypto currency mining who can ruin us and cause harm to ecology and it is the main threat on the internet, the pirates use sophisticated techniques like using a very small power of your processor without without realising it and without clicking on any link despite your web browser is up to date,
and Webassembly Tehnology (WASM) is activated by default in web browsers but

WebAssembly may be used, just like JavaScript, to “steal” processing power instead of data. In 2019, an analysis of 150 different Wasm modules found out that about 32% of them were used for cryptocurrency-mining.

https://training.linuxfoundation.org/blog/webassembly-security-now-and-in-the-future/


Though Wasm has been around for a few years, it rose to prominence more recently when it was used for cryptocurrency mining in browsers. This opened a Pandora's box of potential malicious uses of Wasm.

https://www.virusbulletin.com/virusbulletin/2018/10/dark-side-webassembly/


So I think it's necessary for the average user who does not care about Cryto sites to have peaceful mind that the resources of his computer are not stolen, Zerodot1 is very famous and his list used by many famous software, you can see the list of programs on their sites and it will be great if this list is integrated, thank you !

**Comment by trimechee** [comment]
@Tomatoide, about your legitimate apprehension of false postive, The Ultimate Hosts Blacklist (UHB) said :"All our information is gathered from multiple sources, tested regularly and merged into one massive file which is updated daily. Our hosts can be used on almost all operating system"

**Comment by Tomatoide** [comment]
@trimechee bancuh already has anti cryptominer lists so no need to worry, same goes for ultimate there is already huge lists (and better imo with less aggressiveness and false positives) that bancuh uses.

**Comment by trimechee** [comment]
Brilliant ! Thank you very much for your clarifications :)
