### ISSUE TITLE
Additional Blacklist

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#12]
A user has shared a french sites, that lists some potentially useful hosts file.
http://rlwpx.free.fr/WPFF/hosts.htm

Should investigate and test whether they can improve the adblock.

**Comment by phanluchoa** [comment]
Hi,
Can you add these website to your blacklist ? 
Site: https://sexmoi.net

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque,

Thanks for your suggestion on this. I was having trouble with it because the site is in French. But I think I figured it out. Initially I wanted to add automated unzipping feature to my scripts, but for now, I've decided to just manually download the files and include them directly in this project.

I found 6 different zip files to download. I am skipping the first one.:
```
http://rlwpx.free.fr/WPFF/hblc.7z - anti-hameçonnage (2 mars 2014) : 1 916 sites sensibles
```

I am adding the following:
```
http://rlwpx.free.fr/WPFF/htrc.7z - anti-traqueurs (2 février 2020) : 50 239 sites à possible contenu intrusif bloqués
http://rlwpx.free.fr/WPFF/hpub.7z - anti-publicités (2 février 2020) : 67 646 sites à possible contenu publicitaire bloqués
http://rlwpx.free.fr/WPFF/hrsk.7z - anti-maliciels (2 février 2020) : 47 400 sites à possible contenu dangereux bloqués
http://rlwpx.free.fr/WPFF/hsex.7z - anti-sexe (2 février 2020) : 402 941 sites à possible contenu adulte bloqués
http://rlwpx.free.fr/WPFF/hmis.7z - anti-divers (2 février 2020) : 227 199 sites divers bloqués
```

**Comment by ragibkl** [comment]
This has been deployed to live servers, so I'll close this issue for now.
