### ISSUE TITLE
Do not block Google ads

### ISSUE THREAD

**Issue by net-warriors** [ragibkl/adblock-dns-server#123]
I try ad blockers with the following site:
https://d3ward.github.io/toolz/adblock.html
But in the following DNS, Google ads and xiaomi are not blocked
ipv4: 139.59.219.245
pv4: 139.59.218.207
![1](https://user-images.githubusercontent.com/59220136/155415834-749c586f-6f32-4b02-8930-ac6555842c09.png)

**Comment by Tomatoide** [comment]
it's most likely blocked but after several tests and discusions recently it seems that site is not reliable and results differ from browser to browser even

**Comment by ragibkl** [comment]
This is what I'm getting right now. Seems like we pass 100%?
@Tomatoide , I don't know what enhancements you did to our blacklist sources, but it seems to be working!!

Maybe we close this issue if no more issue?

![image](https://user-images.githubusercontent.com/18181377/182017289-f60c1c07-f56e-4d9e-a97b-411b08cd150a.png)

**Comment by Tomatoide** [comment]
Is this only using bancuh with no other adblockers? if so thats cool! Thanks @ragibkl for your amazing work I think you can close the issue

**Comment by ragibkl** [comment]
Yes. Only on bancuh dns. I'll close this issue now.
