### ISSUE TITLE
Wrong site blocking

### ISSUE THREAD

**Issue by net-warriors** [ragibkl/adblock-dns-server#124]
The w3schools.com site does not work when we use dns  ipv4: 139.59.219.245    ipv4: 139.59.218.207 
it's wrong

**Comment by ragibkl** [comment]
Hi @net-warriors , sorry for late reply. I've been busy. Let me take a look at this.

**Comment by ragibkl** [comment]
Hi @net-warriors ,

I added the whitelist for this in this [commit](https://github.com/ragibkl/adblock-dns-server/commit/99c0e5e7481a5f4cfb7e2081fbf69e407fee67f0). This should work fine now. Do test it and let me know if it's still broken.

Take care!

**Comment by ragibkl** [comment]
Closing this issue. I believe this is fixed already.
