### ISSUE TITLE
Polaris office and canal plus

### ISSUE THREAD

**Issue by trimechee** [ragibkl/adblock-dns-server#125]
Hello, we would like ti thank very very much for adding the amazing "dns over https" feature ! that's amazing, thank you very much Mr @ragibkl :)

I have tried to open the web site of this korean office suite  but I had display problems, by changing to another dns like adguard, I was able to access the polaris site in the normal way :

https://www.polarisoffice.com/en/

  also I used this free vpn "psiphon":
https://psiphon.ca/

to be able to watch the replay of this french tv show on the french canal plus tv website site but it shows me an error message and maybe Bancuh dns is blocking the ads on this site so we can't see the videos  of this website and it will be great if Bancuh Dns can exclude this site from ad blocking and put it on a white list !

https://www.canalplus.com/divertissement/tpmp-partie-1/h/8946028_50013

https://www.canalplus.com/c8/tpmp/touche-pas-a-mon-poste

Thanks very much !

**Comment by ragibkl** [comment]
Hi @trimechee ,

I've fixed for polaris office. Do test it and let me know if it works for you.
I'm not sure about canalplus yet. I'll look into it.

**Comment by trimechee** [comment]
Yes it works fine with polaris office website, thank you very much ! 
for canal plus, I think canal plus has strengthened its protection and detects vpn may be, to be sure, it would be good idea to check with @Tomatoide who is in France apparently and it will be great and helpful if @Tomatoide confirms to us if he can access the canal plus site from france

**Comment by Tomatoide** [comment]
Sorry @trimechee I'm not from france so can't check

**Comment by trimechee** [comment]
@Tomatoide , there is no problem, thank you very much :)
