### ISSUE TITLE
Request add DNSSEC

### ISSUE THREAD

**Issue by georgesaumen** [ragibkl/adblock-dns-server#134]
Hello,

I have used ur DNS server and I very satisfied, it fast, block 99% ads but about block porn I see that it have some of website is not block or u use blacklist host ? But I think to help more secure can u add DNSSEC to all of ur servers ?

Thanks!

**Comment by Tomatoide** [comment]
> but about block porn I see that it have some of website is not block or u use blacklist host ?
> 

#135 should improve this please check again

**Comment by ragibkl** [comment]
Hi all, sorry for late reply. I've been busy with work recently.
I'm not at all familiar with DNSSEC. That is something I have to study.

I can't promise anything for now, but I'll take a look.

**Comment by georgesaumen** [comment]
No problem, thanks!

Vào Th 7, 18 thg 6, 2022 vào lúc 07:10 Ragib Badaruddin <
***@***.***> đã viết:

**Comment by ragibkl** [comment]
@georgesaumen , I don't think this is implemented yet. Is it intentional that you closed this? You don't need this feature anymore?
