### ISSUE TITLE
Request add this porn website to blacklist

### ISSUE THREAD

**Issue by georgesaumen** [ragibkl/adblock-dns-server#136]
Hello,

I have some website that contains pornography but it not blocked yet on ur DNS:

sextop1.lol
xvideos98.xxx
phimsex69.link
[clip3x.org](http://clip3x.org/)
[vlxyz.net](http://vlxyz.net/)
[sexvnx.pro](http://sexvnx.pro/)
[xxtv.pro](http://xxtv.pro/)
[sexindrag.com](http://sexindrag.com/)
phimsex.cam
s.phimsex.cam
[viet69.app](http://viet69.app/)
lontv.cc
[sexau.xyz](http://sexau.xyz/)
[webphimsex.pro](http://webphimsex.pro/)
[sex88.tv](http://sex88.tv/)
[asian-sex.pro](http://asian-sex.pro/)
cliphot69.cc
[phimsexvn.pro](http://phimsexvn.pro/)
[sextinh.net](http://sextinh.net/)
vietsex.club
sexphim.vip
[clip-sex.biz](http://clip-sex.biz/)
[phimsexmy.biz](http://phimsexmy.biz/)
[sexhay69.mobi](http://sexhay69.mobi/)
phimsexjav.cc
[phe69.com](http://phe69.com/)
[anhphimsex.com](http://anhphimsex.com/)
[phimsexthai.net](http://phimsexthai.net/)
phimsexthu.site
[lamtinh.pro](http://lamtinh.pro/)
[vl88.pro](http://vl88.pro/)
[xemsextop.net](http://xemsextop.net/)
[sexhiep.com](http://sexhiep.com/)
[phim.damvodoi.com](http://phim.damvodoi.com/)
[damvodoi.com](http://damvodoi.com/)
[sexzz.me](http://sexzz.me/)
sexnhat.club
phimsexhay.monster
[cuongsex.com](http://cuongsex.com/)
phimsexnguoilon.top
[zsexmoi.com](http://zsexmoi.com/)
[xxhot.tv](http://xxhot.tv/)
sexditnhau.cc
[sex3x.xyz](http://sex3x.xyz/)
lon88.vip
[phimsex789.net](http://phimsex789.net/)
[sexvietx.com](http://sexvietx.com/)
phimhd.sex
[sexfullhd.pro](http://sexfullhd.pro/)
[sexkhongche.mobi](http://sexkhongche.mobi/)
[phimsexdam.me](http://phimsexdam.me/)
[gaigoi18.pro](http://gaigoi18.pro/)
[sexhayvc.biz](http://sexhayvc.biz/)
[vlphimsex.org](http://vlphimsex.org/)
sexviet.tube
[sexmoihay.pro](http://sexmoihay.pro/)
phimxxx.lol
[sextop18.net](http://sextop18.net/)
[javnhatban.com](http://javnhatban.com/)
[hihisex.biz](http://hihisex.biz/)
[sexhay123.com](http://sexhay123.com/)

Can u add all of this to ur blacklist ?

Thanks!

**Comment by ragibkl** [comment]
Hi @georgesaumen ,

Sorry for late reply. I've been busy at work recently.

Thanks for the suggestion. I've added them [here](https://github.com/ragibkl/adblock-dns-server/commit/46477a0c0fe5f51461774e4a1eff8f78052eca73) in the latest master. It should take effect on all our servers soon in few minutes.

Please test it out, and close this ticket if everything works well.
