### ISSUE TITLE
Add /dns-query suffix to DoH addresses

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#153]
Most apps used to change dns expects a /dns-query suffix as most DoH addresses have that and when it doesn't find it it doesn't register successfully, so eg `https://sg-dns1.bancuh.com/` should become `https://sg-dns1.bancuh.com/dns-query`

**Comment by Tomatoide** [comment]
and for simplification maybe remove 'dns' from address so it becomes `https://fr1.bancuh.com/dns-query`

**Comment by ragibkl** [comment]
I'll take a look. I think not hard to do. Let me try.

**Comment by ragibkl** [comment]
> and for simplification maybe remove '-dns' from address so it becomes `https://fr1.bancuh.com/dns-query`

I cannot support 1 server having 2 domains. So if we add `fr1.bancuh.com` on the server, I have to remove the existing `fr-dns1.bancuh.com`. I'm worried that we already have users who depend on the existing `fr-dns1.bancuh.com`, and their internet will be interrupted.

**Comment by Tomatoide** [comment]
> Hi @Tomatoide ,
> 
> > Most apps used to change dns expects a /dns-query suffix as most DoH addresses have that and when it doesn't find it it doesn't register successfully, so eg `https://sg-dns1.bancuh.com/` should become `https://sg-dns1.bancuh.com/dns-query`
> 
> If you look at the following [lines](https://github.com/ragibkl/adblock-dns-server/blob/master/adblock_dnsdist/dnsdist.conf#L19-L21), it seems that we already have this support earlier. Could you test again?
> 
> ```
>     -- add a DoH resolver listening on port 443 of all interfaces
>     addDOHLocal('0.0.0.0:443', certFile, keyFile, { '/', '/dns-query' }, { doTCP=true, reusePort=true, tcpFastOpenSize=0 })
>     addDOHLocal('[::]:443', certFile, keyFile, { '/', '/dns-query' }, { doTCP=true, reusePort=true, tcpFastOpenSize=0 })
> ```

It does work 👍 thank you.



> > and for simplification maybe remove '-dns' from address so it becomes `https://fr1.bancuh.com/dns-query`
> 
> I cannot support 1 server having 2 domains. So if we add `fr1.bancuh.com` on the server, I have to remove the existing `fr-dns1.bancuh.com`. I'm worried that we already have users who depend on the existing `fr-dns1.bancuh.com`, and their internet will be interrupted.

No worries 👍

**Comment by ragibkl** [comment]
I should probably update the doh list on the bancuh website. I'll do that so it's clear. Thanks for raising this!
