### ISSUE TITLE
Is this Bancuh Adblock DNS no logs?

### ISSUE THREAD

**Issue by sabatachi** [ragibkl/adblock-dns-server#158]

**Comment by ragibkl** [comment]
The server keeps logs for 10 minutes max. There is a log viewer page that you can use, but it will only show logs for your own ip address.

Ideally I don't want to keep any logs at all for users' privacy, but it's needed for debugging sites that might break or ads that aren't yet filtered. This is especially true on mobile and apps where we don't have browser dev tools.

I figured that 10 minutes and ip address restrictions view limit is a good balance of debugging utility vs user privacy.

I hope that answers your question.

**Comment by sabatachi** [comment]
understood.Thank you for your prompt reply.

2022年8月31日(水) 21:54 Ragib Badaruddin ***@***.***>:

**Comment by ragibkl** [comment]
I think at the `bind` level, it does have more logs, but it doesn't have any user ip address. It only have the ip address from `dnsdist` level, which is just internal ip.

I should probably clean that up since it's not useful for debugging. I should capture this task as a separate issue.

**Comment by ragibkl** [comment]
Hey @sabatachi , if your question is answered, please close this issue.
