### ISSUE TITLE
Both my websites are blocked by the DNS.

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#16]
Hi, how's it going? 

I've just noticed that my two websites https://dunkerquestreetradio.eu and dunkerquestreetradio.fr are blocked by Bancuh? It's possible to put him on a white list. Thanks

**Comment by TechComputerServiceDunkerque** [comment]
is to fix, to understand nothing

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque

Thanks, for reaching out. We can test as follows:
```
nslookup dunkerquestreetradio.eu dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
Name:	dunkerquestreetradio.eu
Address: 185.26.105.244
```
```
nslookup dunkerquestreetradio.fr dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
Name:	dunkerquestreetradio.fr
Address: 151.80.67.116
```

I think the results look ok. They are not being blocked.
