### ISSUE TITLE
Request DNS location for Vietnam

### ISSUE THREAD

**Issue by georgysaumen** [ragibkl/adblock-dns-server#160]
Hello,

I have used ur service and I vey happy that your service is very good, it help me many things but I have one problem is can u help me add one or two servers in Vietnam (I know that servers Singapore is in Asia and very usuable with me but I want to have a vey low ping for watch video or play games or sth). Can u develop one or two servers in Vietnam ? It better for me. 

I have see a VPS that located in Vietnam is: https://123host.vn/en/cheap-cloud-vps-service.html

Thanks!

**Comment by ragibkl** [comment]
It seems that there are several other VPS providers in Vietnam as well.
https://blog.servermania.com/vps-vietnam/

But your suggestion seems to be okay. I'll try it out and will update here.

**Comment by ragibkl** [comment]
Saw this as well: https://www.ovhcloud.com/asia/vps/vps-vietnam/
They market towards vietnam users, but the servers are actually in SG and AU.

**Comment by georgesaumen** [comment]
> It seems that there are several other VPS providers in Vietnam as well. https://blog.servermania.com/vps-vietnam/
> 
> But your suggestion seems to be okay. I'll try it out and will update here.

I think some vps on this is OK and a VPS provider I see it best is 123host (https://123host.vn/en/cheap-cloud-vps-service.html) because I have located my website on there and it good

**Comment by georgesaumen** [comment]
> Saw this as well: https://www.ovhcloud.com/asia/vps/vps-vietnam/ They market towards vietnam users, but the servers are actually in SG and AU.

I think it not, because u have two servers in Singapore already, I want a servers located in Vietnam.

**Comment by ragibkl** [comment]
I think I'll try with 123host when I have the time. I'll let you know.

**Comment by georgesaumen** [comment]
Thanks

Vào Th 3, 6 thg 9, 2022 lúc 07:29 Ragib Badaruddin ***@***.***>
đã viết:

**Comment by ragibkl** [comment]
I tried 123host cloud VPS. They block UDP traffic, so when I run bind server, it doesn't work. I already requested they open this up, but they won't.
![image](https://user-images.githubusercontent.com/18181377/188770167-a068c7b6-30b2-49c9-b4c0-052431a56bb8.png)

Fuck me! I already wasted money on this!

**Comment by ragibkl** [comment]
To their credit, the response on support ticket is very fast. Block UDP maybe prevents spam from some users. But it doesn't work for me since I need to run DNS.

Well, I guess my use case is not like other people.

**Comment by georgesaumen** [comment]
😥

Vào Th 4, 7 thg 9, 2022 vào lúc 09:03 Ragib Badaruddin <
***@***.***> đã viết:
