### ISSUE TITLE
Request add this blocklist to dns server

### ISSUE THREAD

**Issue by georgysaumen** [ragibkl/adblock-dns-server#164]
Hello,

Can u help me add these youtube adblock host lists to ur dns ?

Thanks

https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt

**Comment by ragibkl** [comment]
@Tomatoide , What do you think of this one? Makes sense to add it?

**Comment by Tomatoide** [comment]
we already have goodbyeads youtube list which is quite similar, we can add this list and test it but these dns based lists doesnt really block ads on youtube

**Comment by ragibkl** [comment]
Okay, I read the reviews posted by other users on the project's issues page [here](https://github.com/kboghdady/youTube_ads_4_pi-hole/issues). Seems like users reported issues that YouTube stopped working after using this, and that youtube ads aren't blocked at all. I think it's probably not worth to add this in.

Thanks @Tomatoide for your input.
