### ISSUE TITLE
Add a up/down time moniter

### ISSUE THREAD

**Issue by 0GHatMak3r** [ragibkl/adblock-dns-server#170]
Just as the title

**Comment by ragibkl** [comment]
Hey @0GHatMak3r , what kind of monitor do you have in mind? Do you have any specific ideas?

**Comment by ragibkl** [comment]
Currently looking at https://github.com/louislam/uptime-kuma

**Comment by ragibkl** [comment]
@0GHatMak3r , I've created a page using uptime-kuma.

https://status.bancuh.com/

@Tomatoide , @phanluchoaofficial , do take a look at the page and let me know what you think.

**Comment by Tomatoide** [comment]
That's cool! very nice work @ragibkl 👍

**Comment by ragibkl** [comment]
I'll make more improvements on the side. But for now I think we can close this.
