### ISSUE TITLE
Consider blocking .zip domains

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#174]
Reference: https://www.youtube.com/watch?v=LFriS1PICE0

Seems like `.zip` domains can easily be abused to trick users into downloading a malicious file.

I'll look into implementing the following:
- Block all `.zip`
- use a smart list to block, only bad actor domains. Maybe use this list: https://github.com/trickest/zip

**Comment by ragibkl** [comment]
@Tomatoide and @phanluchoaofficial , do let me know what you think.

**Comment by Tomatoide** [comment]
Not sure about this, I think would prefer blocking only bad domains, also the trickest list seems to block All .zip domains and is not a smart list it seems

**Comment by ragibkl** [comment]
Ok, point taken. In that case, let's not do this for now. I'll close this issue.
