### ISSUE TITLE
Avoid blocking trackers like "google-analytics" and "googleads.g.doubleclick" to avoid break websites and make payment services and applications unusable

### ISSUE THREAD

**Issue by trimechee** [ragibkl/adblock-dns-server#175]
Hello, thank you very much for these awesome wonderful dns servers ! 🥇 💯 

Please i have request, there is fundamental problem, all dns lists break websites and make payment services and applications unusable.....because of blocking trackers that's why it's better to make lists and dns that just block ads and not the trackers, I tried a lot of mini light basic light minimal blocklists supposed to not contain false positives and not breaking the experience of apps, but I find that all the basic light even minimal light lists on the web apparently block these sites essentials:

google-analytics.com

googleads.g.doubleclick.net
 
for example I tried the lists of 1Hosts (mini), Disconnect, oisd-basic, adguard, control d, HaGeZi - Multi LIGHT, ph00lt0.....

but these important services "google-analytics" or "googleads.g.doubleclick" are blocked while they are essential for many sites and apps and services....

it doesn't matter if we see some ads, the most important thing is that all the sites work and we can be content with a basic blocking of the most malicious heavy ads, google is a well-known company so we have nothing to do fear but if there may be concern for privacy, there is virus malware theft....
this problem can be solved by not blocking trackers or at least tracking them from big companies like google and amazon, it will be great to make a list with in whitelist domains and trackers from big companies that we can find them here after doing this test:

https://d3ward.github.io/toolz/adblock.html

  so it will be great to have a special list or dns that doesn't block trackers to avoid bugs:

  "I suppose the same could be said about Google Ads which now breaks Google's partner ad settings interface.

Blocking these types of domains which breaks smaller services that aren't used as much I can understand, but when you have large scale applications being broken it may be time to look at improving the approach such as possibly splitting the AdGuard DNS filter into many smaller lists for more granular control."

urgent need to be unblocked:

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1335

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1142

https://github.com/AdguardTeam/AdguardFilters/issues/150327

https://github.com/AdguardTeam/AdguardFilters/pull/90357

The interest of dns blockers is to avoid installing an app or extension on our smartphone or computer which can be heavy and run in the background and use up battery and ssd, and the dns must be functional because it is not possible to deactivate the domains that we want manually in the dns and there are several subdomains, otherwise the dns block loses all interest if websites are broken and service does not work, so my request please and to make a list for ublock origin and for dns servers that allow to use custom lists in "rethink dns" and "ahadns blitz" and "control d" dns and "opennic dns" and "nextdns"....

and this list only blocks ads and does not block trackers like "google-analytics" and "googleads.g.doubleclick and amazon trackers.....to avoid false positives and the breakdown of services and site breakages website, thank you very much!

the list of trackers not to be blocked can be found on this site:

https://d3ward.github.io/toolz/adblock.html

**Comment by ragibkl** [comment]
@Tomatoide , what's your opinion on this?

**Comment by Tomatoide** [comment]
What are examples of sites or apps broken by blocking these domains?

**Comment by trimechee** [comment]
"I guess I have to challenge this at least once as it's simply too problematic. For example, https://github.com/AdguardTeam/AdguardFilters/pull/90357 alone, not resolved in DNS, has been [wasting](https://twitter.com/zumusata366/status/1508051498772889608) a [lot](https://twitter.com/search?q=adguard%20paypay&src=typed_query&f=top) of precious time of user, [losing](https://twitter.com/TK_NiMeC3/status/1419997642952609793) financial opportunity, and [causing](https://twitter.com/koumei_wana/status/1576796190183604224) you to lose new user1. There are more - [this](https://twitter.com/otr_da_wa_3/status/1655738351314690050) repo has around 10+ GA-related issues and TPF has 200+ exception, and today I found this can be solved if GA is unblocked on DNS without allowing in contents filtering. Note this is not only a matter of DNS user but also of those using DNS filtering on apps. As discussed in Slack in past, there will be many user who only want to block ads and not tracker, but those who want to block GA can still do with personal DNS or with any of client-side AG products. Privacy advocates will critisize you and me if it's done, but the qustion is the total utility of all user.

Of note someone already [asked] (https://twitter.com/miniamaruDEBU/status/1372024462149779456) paypay to solve the issue.


https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1335

**Comment by trimechee** [comment]
Paypay's external service binding still fails. After thinking about it for about an hour, I found out that Adguard was the cause. It wasn't the smartphone I always use, so I forgot that Adguard was running in the background. If you have any problems, you should first suspect Adguard. How many times was this pattern repeated?


https://twitter.com/zumusata366/status/1508051498772889608
