### ISSUE TITLE
Use Hagezi list for one of dns servers

### ISSUE THREAD

**Issue by trimechee** [ragibkl/adblock-dns-server#176]
Hello, I know Banch dns has wonderful lists , and also i suggest to add  Hagezi list to one of the dns servers because i discover that Hagezi  revolutionary blocklists recommanded by many users and experts ! 🥇 💯

https://github.com/yokoffing/NextDNS-Config#blocklists-1

https://github.com/yokoffing/filterlists

and my suggestion is to use one of the hagezi lists  like Multi PRO - Extended protection or Multi PRO++ - Maximum protection or Multi ULTIMATE - Aggressive protection  and merge them with anti crypto jacking miners coins because  the fundamental problem in the web actually is the dangerous hidden secret crypto currency mining the pirates use sophisticated techniques like using a very small power of our processor without realising it....

https://github.com/hagezi/dns-blocklists

i search and i find these amazing anti cryptojacking lists, it will be great to integrate them to Multi PRO++ - Maximum protection or Multi ultimate - Aggressive protection  in one of the dns servers, beacause there is no great interest in having all Bancuh dns servers with the same blocklists and filters because users have different needs from each other, for example we can put one of our beloved Bancuh dns dns only in the smart tv or in a web browser dedicated to entertainment and video streaming and not for professional use.....

so no more need for ad blocker or ad blocking app that runs in the background and uses the battery, in addition with the manifest v3, traditional ad blockers risk becoming less effective so having a dns that blocks all ads will be the remedy, thank you very much!

https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt
https://blocklistproject.github.io/Lists/adguard/crypto-ags.txt
https://blocklistproject.github.io/Lists/crypto.txt
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_UBO.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_browser
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser_AdBlock.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_optional
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_optional.txt
https://raw.githubusercontent.com/olbat/ut1blacklists/master/blacklists/cryptojacking/domains

**Comment by Tomatoide** [comment]
Added hagezi in #177

**Comment by trimechee** [comment]
@Tomatoide  Great awesome ! Thank you so much :)

**Comment by ragibkl** [comment]
Thanks @Tomatoide  for looking into this. I've merged your pull request.
Thanks @trimechee for the suggestion.

**Comment by trimechee** [comment]
@ragibkl  Awesome fantastic marvellous !! Thank you so much :) 💯 🥇

**Comment by trimechee** [comment]
i suggest Hagezi list beacuase after many many searches, hagezi has the most complete blocklist and the developer of hagezi blocklist is very responsive to remove false posts, I checked in "rethink dns blocklists " and hazigui blocks almost a million elements unlike other famous dns blocklists which only blocks 200k or 400k elements .... hazigui is the most powerful list on the web without a doubt

**Comment by Tomatoide** [comment]
We are now using Hagezi lists, thanks for your suggestion 👍

**Comment by trimechee** [comment]
Awesome ! Thank you so much :) 👍 💯 🥇

**Comment by Tomatoide** [comment]
You're welcome, also added more anti cryptominer lists in latest commit

**Comment by trimechee** [comment]
@Tomatoide Magnificent Awesome ! Bancuh adblock-dns-server was already one of the very best dns on the planet and now continues to remain one of the best dns in the world if not the best with innovations and new reliable filters ! 👍 💯 🥇 

I heard about Bancuh adblock-dns-server in a French article on the free forum which recommends Bancuh adblock-dns-server which is the best dns to block complex ads...thank you very much for all your efforts to do this beautiful DNS :)

**Comment by Tomatoide** [comment]
Thanks to @ragibkl for this awesome project and his continous work! 👍

**Comment by trimechee** [comment]
Yes of course many thanks for the great Mr @ragibkl for his awesome work to make these awesome DNS :) 🥇
