### ISSUE TITLE
Typosquatting protection 

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#178]
https://github.com/RPiList/specials/tree/master/Blocklisten
Was already added Domainsquatting protection but recent problem it changed to abp syntax and I don't know if bancuh supports it (used older version 'domains' of list as a workaround in latest patch)

Many lists are now moving on from hosts/domains syntax to ABP, DNSmasq, Domains (wildcards), Regex, or Response Policy Zone, as put by OISD.nl maintainer: '' Effectively, the blocklists using ABP, DNSmasq, Domains (wildcards), Regex -syntaxes are about 4 times smaller than HOSTS / Domains -syntaxes, AND block MORE. This is not something new, and has been known for years. ''

Thanks.

**Comment by ragibkl** [comment]
We don't support ABP syntax right now. Adblock plus can do a lot more as it operates on users browser. For example, it can filter by specific url paths, or by regex on the paths
We operate only at the DNS layer, so we can only do something on the domain or sub-domain.

But, it seems that some of the ABP blocklist is just a different way to write domains and hosts. So maybe we can at least use those entries, and ignore the path filters?

> Many lists are now moving on from hosts/domains syntax to ABP, DNSmasq, Domains (wildcards), Regex, or Response Policy Zone, as put by OISD.nl maintainer: '' Effectively, the blocklists using ABP, DNSmasq, Domains (wildcards), Regex -syntaxes are about 4 times smaller than HOSTS / Domains -syntaxes, AND block MORE. This is not something new, and has been known for years. ''

For each of the formats that you listed here, please find an example source file that you would like to try, and I can try to add support for it in Bancuh DNS.

**Comment by ragibkl** [comment]
I'm looking at this example file: https://github.com/RPiList/specials/blob/master/Blocklisten/DomainSquatting/AT/AddikoBank

```
||1ddiko.at^
||1ddiko.com^
||2ddiko.at^
||2ddiko.com^
||a-ddiko.at^
||a-ddiko.com^
```
Is this what you mean by ABP syntax? I think if it's limited to this, maybe we can support it. Let me try.

**Comment by Tomatoide** [comment]
yes we can try that 
Also, just to be sure, bancuh supports rpz right? because added some rpz lists in latest commit

**Comment by Tomatoide** [comment]
I think the workaround implemented is good for now, so I'll close this issue for now, thanks
