### ISSUE TITLE
Servers down 

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#185]
Hi @ragibkl , it looks like all servers are down (except sg-dns2 for some reason) , hope you can take a look at it, thanks

**Comment by ragibkl** [comment]
![image](https://github.com/ragibkl/adblock-dns-server/assets/18181377/30993b49-cda4-4b1d-a987-167463444edc)
For some reason, the dns process was just high cpu for no reason.

**Comment by ragibkl** [comment]
![image](https://github.com/ragibkl/adblock-dns-server/assets/18181377/590a4988-0cd7-4ff7-891d-61d9be2d77dd)
The compiler is also taking lots of cpu. It should only do that every 24 hours to compile the adblock list.
