### ISSUE TITLE
New list filter

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#19]
Hello, as promised I will share with you my discoveries of filters for your dns. 

- https://lists.noads.online/lists/compilation.txt
- https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts-online.txt
- https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt
- https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-LeEco-Extension.txt
- https://pgl.yoyo.org/as/serverlist.php?showintro=0;hostformat=hosts
- https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
- https://someonewhocares.org/hosts/zero/hosts
- http://sbc.io/hosts/hosts
fter it's up to you, the problem of ads is still not solved, they appear more and more and new popup/overlays are born :/

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque , 

I've added them and deployed to live version. I noticed that some of them have duplicates. I'm just gonna add them now, and  let my scripts deal with the duplicates. I hope there are improvements after adding this list.

Let me know if any issues and comment here.

**Comment by ragibkl** [comment]
It turns out that the source https://lists.noads.online/lists/compilation.txt does is not a hosts file format. I had to remove this file.

**Comment by TechComputerServiceDunkerque** [comment]
News List

**Advertising Lists (02/2020)**
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts

**Suspicious Lists**
https://hosts-file.net/grm.txt

**Tracking & Telemetry Lists**
https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

Thanks again for the new suggestions.
I will keep this issue ticket closed. I've copied your suggestion over to a new ticket at https://github.com/ragibkl/adblock-dns-server/issues/24
