### ISSUE TITLE
Can't see logs

### ISSUE THREAD

**Issue by CasanierV** [ragibkl/adblock-dns-server#193]
Long time no see, Ragib.
Today I couldn't open the log page and found that it changed the URL. 
But when I typed in the new URL, I found this message.

This 103.29.68.118 page can’t be found
No web page was found for the web address: http://103.29.68.118:8080/
HTTP ERROR 404

Does this problem only happen to me?

**Comment by Tomatoide** [comment]
Happens to me too, but it's just a blank page

**Comment by ragibkl** [comment]
Hi, I rewrote the logs component in Rust, and looks like I didn't make the logs endpoint the same. My bad!

Can you try adding `/logs` at the end? I think that should work.

**Comment by ragibkl** [comment]
I've also updated the faq page with the correct logs link: https://bancuh.com/faq
They should all have the `/logs` in the end now. I hope this fixes it.

**Comment by CasanierV** [comment]
It's not a blank page anymore, but there's still no log.

It shows:

ip address: ::ffff:1.2xx.x.xx
Query	Answers

There was no 'ffff' part before, I don't know if that's the reason.

**Comment by ragibkl** [comment]
Ok, I'll have to test it myself as well. I don't use ipv6 at home, so l'll turn that on here and see if I can replicate the issue.

**Comment by ragibkl** [comment]
@CasanierV , I pushed a new update to `dnsdist-acme`. Could you try this again?

**Comment by CasanierV** [comment]
Thank you, nothing is wrong now except for sg1.

SG1's log page is so slow that it won't open, I don't know why. It shows ERR_CONNECTION_ABORTED.
(But I don't use SG1 so it doesn't matter.)

Also the logs-ipv6 page won't open in my browser, but ipv4 is fine.

Thank you for all you do!

**Comment by ragibkl** [comment]
Yeah, something's wrong with sg1. I agree.
I'll have to investigate that separately.

**Comment by ragibkl** [comment]
@CasanierV , I pushed a new change to `dnsdist-acme`
If you have time, do test it out and let me know if it helps to see logs again.

**Comment by CasanierVI** [comment]
Sorry, I'm just finding out about this now.
I've deleted my account, so I've reapplied for a new one.
I think SG1 should be fine now, but the log page of SG2 can't be opened, I don't know why.

**Comment by CasanierVI** [comment]
And I found a problem with SG1 and SG2, it is not possible to open an image from a certain website.
The image needs to be loaded into the domain "img3.readpai.com", but SG can't resolve this domain.
But FR and JP can resolve it. I don't know why there is such a difference.

**Comment by CasanierVI** [comment]
@ragibkl  I found a problem with SG1 and SG2, it is not possible to open an image from some websites.
The image needs to be loaded into the domain "img3.readpai.com", but SG can't resolve this domain.
But both FR and JP can resolve it. I don't know why there is such a difference.

**Comment by ragibkl** [comment]
@CasanierVI , for some reason, in sg, the forwarders we use `95.85.95.85,2.56.220.2` can't resolve that domain.
Maybe I'll revert sg to google dns for now.

Looks like I have to expedite work on the recursive resolver mode.

**Comment by CasanierVI** [comment]
I just happened to find this problem when I was testing SG's log page. It's not a big problem, and I don't usually use SG that much, so I don't think you need to change it.
(But it looks like it has already changed)

However, it seems that the SG2 log page still can't be opened, I don't know what's causing this.

**Comment by CasanierVI** [comment]
@ragibkl 
I just happened to find this problem when I was testing SG's log page. It's not a big problem, and I don't usually use SG that much, so I don't think you need to change it.
(But it looks like it has already changed)

However, it seems that the SG2 log page still can't be opened, I don't know what's causing this.
