### ISSUE TITLE
Brave search blocked

### ISSUE THREAD

**Issue by weedenbc** [ragibkl/adblock-dns-server#194]
https://search.brave.com/ (the default search engine for the Brave browser) does not resolve.

**Comment by CasanierV** [comment]
cdn.search.brave.com
imgs.search.brave.com
tiles.search.brave.com
These domains are blocked.
It may be necessary to put *.search.brave.com 
on a white list to make it work.

**Comment by ragibkl** [comment]
I've added the whitelist here: https://github.com/ragibkl/adblock-dns-server/commit/0da03a0efe67431296aa8350769ddf1f06cb445c

Let's see if this will fix it.
At the same time, might be worth to bump the update frequency from once / day, to once / hour? I don't know if it will impact server downtime, but might give it a shot.

**Comment by ragibkl** [comment]
@weedenbc , I think it's fixed now. Can you test it on your side?

**Comment by weedenbc** [comment]
Seems to be working now! Thanks.

**Comment by ragibkl** [comment]
I'm closing this issue now since it's resolved. Thanks all!
