### ISSUE TITLE
Change backend forwarders

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#195]
Hello, so until we get handling of domain resolution recursively, can we change to something other than google? eg gcore here is performance in my area: 

![IMG_20240107_173012](https://github.com/ragibkl/adblock-dns-server/assets/6270814/792cd100-88b0-4bf8-8e14-288570b8a280)
Thank you for your awesome work

**Comment by ragibkl** [comment]
Sure, I'll take care of it.

**Comment by ragibkl** [comment]
I've updated all servers to use gcore public dns. https://gcore.com/public-dns

No code changes, since I have to manually ssh into each servers to update the `.env` files and manually restart the services. Unfortunately, there isn't a way for you to verify that I made the changes correctly.

**Comment by Tomatoide** [comment]
Thanks @ragibkl ! I think you can verify with dnsleaktest website, and the difference for me at least seems noticable 👍 also I used dnsperf website for test above for future reference
