### ISSUE TITLE
unblocking site

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#20]
Bonjour, 

the following site is blocked when it shouldn't be, thanks for the work you provide :)

https://ed-protect.org/bI16pCauPb

**Comment by ragibkl** [comment]
this is done is latest version. I will close this issue now, but you can reopen if issue persists.

**Comment by TechComputerServiceDunkerque** [comment]
I'm annoyed the dns is now blocking uptobox.com... Possible to whitelist the site, thank you.

**Comment by ragibkl** [comment]
I've whitelisted this in latest version and is running now. Thanks for the report.
