### ISSUE TITLE
Youtube Adblock

### ISSUE THREAD

**Issue by phanluchoacom** [ragibkl/adblock-dns-server#203]
Hello,

Can you please add this host file to your server for help block ads in youtube? 

IPV4: https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv4.txt
IPV6: https://ewpratten.github.io/youtube_ad_blocklist/hosts.ipv6.txt

Thanks!

**Comment by ragibkl** [comment]
Hi @phanluchoacom , thanks for the report. I appreciate every user suggestion and feedback we get. There's always something to be gained.

I've given this some thoughts, and I think @Tomatoide is right in this case. I took a look at the list, and it seems to just list out various *.googlevideo.com domains. While they may contain youtube ads, they also potentially contain regular youtube videos or other google videos content.

I am worried that adding the list will break some regular content for users.

However, I'm willing to test this out! I'm setting up `jp-dns3` server.

```
jp-dns3.bancuh.com
ipv4: 139.162.121.126
ipv6: 2400:8902::f03c:94ff:fe29:1a27
```

Please try it out for a few days and let us know if it works!

**Comment by CasanierD** [comment]
I still see ads. I guess the DNS blacklist doesn't work for YouTube.

;rr3---sn-8pcv-u2xk.googlevideo.com.IN TYPE65	
;rr3---sn-8pcv-u2xk.googlevideo.com.IN A	
rr3---sn-8pcv-u2xk.googlevideo.com. 600 IN CNAME rr3.sn-8pcv-u2xk.googlevideo.com.
rr3.sn-8pcv-u2xk.googlevideo.com. 600 IN A 103.5.32.142

**Comment by ragibkl** [comment]
Hi @phanluchoacom, @CasanierD , @Tomatoide 

Thanks for all your contribution and testing efforts. I think we can conclude that this won't work very well.
I'll close this issue and shut down sg-dns3.
