### ISSUE TITLE
Pangle ads on eSound (Update ^-^)

### ISSUE THREAD

**Issue by RAiNYRENJi** [ragibkl/adblock-dns-server#207]
![Screenshot_20240411_182906.jpg](https://github.com/ragibkl/adblock-dns-server/assets/161404404/4aa40524-0d80-4dd9-8c58-925814f0c820)

![Screenshot_20240411_182311.jpg](https://github.com/ragibkl/adblock-dns-server/assets/161404404/1d6abf8b-6cb9-4e14-a59b-ddba2ccbeaa3)

These ads appear on eSound (and really annoying)...

Is it possible to block these ads?

**Comment by ragibkl** [comment]
Hi. Can you test the app while using our dns? Then see if anything show up in the logs.
Logs endpoint in the faq page. `https://bancuh.com/faq`

Look for any ads domain that might show up.

I tried the app myself and looks like ads are blocked. Maybe they are using different ad servers for your location.

**Comment by ragibkl** [comment]
Hi. That's interesting. If there's no adserver to block, there's not much we can do.

If you disable bancuh dns, do you see the same ads?

My guess is that they try to load ads from pangle domains, but when it fails, it just fallbacks to that hardcoded ads.

Also possible that they load ads on the same domain as the app's music data api. This we cannot block.

Another possibility is they don't use domain names, but just load ads using ip address directly. This I think is less likely.

**Comment by ragibkl** [comment]
@RAiNYRENJi , can I know what phone you are using? I'm worried if your phone manufacturer is also injecting all these ads into your apps.

I tried the eSound app myself, and I don't see any ads when I use bancuh dns.

**Comment by ragibkl** [comment]
Hi @RAiNYRENJi , in that case, I don't think we can do anything for this. Please close this ticket if you're done testing.

Of course, feel free to open another issue ticket for other feedback in the future.

Thanks for your contribution and for using bancuh dns!

**Comment by ragibkl** [comment]
@RAiNYRENJi , I've added that here in the latest [commit](https://github.com/ragibkl/adblock-dns-server/commit/baa4bda6ae6e070b0060a997dc3e7525ce66c85f). Let's see if it works.

**Comment by ragibkl** [comment]
@RAiNYRENJi , any updates? Did you test our bancuh dns after I added that to the blocklist?

**Comment by ragibkl** [comment]
Ok, I think need to block `*.mediation.unity3d.com`. I've pushed a commit here: https://github.com/ragibkl/adblock-dns-server/commit/6a6f3df7220cca55335694cc59e1b77af108c0f0

I have restarted sg servers so you can test again. Please test and report here.

**Comment by ragibkl** [comment]
@RAiNYRENJi , that's good to know! Looks like you were able to find the right ad domain to block! Nice!

I did a quick search, looks like there are other projects that also block some part of `*.mediation.unity3d.com` domain. https://github.com/search?q=mediation.unity3d.com&type=code .

I think we are done here. If you are happy with your testing, please close this ticket.

Thanks for your contribution!
