### ISSUE TITLE
DNS server option for a toned down protection

### ISSUE THREAD

**Issue by RAiNYRENJi** [ragibkl/adblock-dns-server#208]
I really like the DNS because it enforces SafeSearch but keeps the YouTube comments unblocked and blocks NSFW sites. A better version of CleanBrowsing DNS, I would say.

But a bit of a problem is that it's a bit too aggressive. Legitimate sites are blocked, like Google AdSense for legitimate purposes. And the adblocking is fine; it's just having to open sites like, for example, modified APKs with Anti-Adblock on their sites, which is just a hassle. Having both the devices and the router with the DNS setup is going to be a pain to use a different DNS like Google or Cloudflare since it's gonna be blocked or ineffective.

So here's the idea:

A DNS server option that:
☑️ Blocks trackers/analytics/bug reports
☑️ Blocks NSFW sites
☑️ Enforced SafeSesrch but YouTube comments unblocked
☑️ Blocks Bypass Methods
☑️ Blocks malicious/hidden redirect ads but **keep the good ads unblocked.**

Why? This:

![Screenshot_20240416_120725.jpg](https://github.com/ragibkl/adblock-dns-server/assets/161404404/1426230b-dc41-4352-bcf4-3246d1aff5d4)

![Screenshot_20240416_120636.jpg](https://github.com/ragibkl/adblock-dns-server/assets/161404404/94bab2e6-7b67-47fa-847a-540945fc944e)

![Screenshot_20240416_120653.jpg](https://github.com/ragibkl/adblock-dns-server/assets/161404404/4894c532-c03b-4cb1-bf95-058fae72f1de)

Here are also filterlists that come in handy:

- [Hagezi Pop-up Ads](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#tada-pop-up-ads---protects-against-annoying-and-malicious-pop-up-ads-)
- [Hagezi Threat Intelligence Feeds](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#closed_lock_with_key-threat-intelligence-feeds---increases-security-significantly-recommended-)
- [Hagezi Fake](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#trollface-fake---protects-against-internet-scams-traps--fakes- )
- [Hagezi Bypass](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#outbox_tray-dohvpntorproxy-bypass---prevent-methods-to-bypass-your-dns-)
- [Hagezi SafeSearch Unsupported Sites](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#mag-safesearch-not-supported---prevent-the-use-of-search-engines-that-do-not-support-safesearch-)
- [Hagezi Native Trackers](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#native)
- [OISD NSFW](https://oisd.nl/setup)
- [Hagezi Gambling](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#gambling)
- [Hagezi Piracy](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#piracy)

**Comment by ragibkl** [comment]
@Tomatoide , what do you think of this?

**Comment by ragibkl** [comment]
> Having both the devices and the router with the DNS setup is going to be a pain to use a different DNS like Google or Cloudflare since it's gonna be blocked or ineffective.

Hi @RAiNYRENJi , I don't think this is a problem. If you use the dns setup on your router, you can still override that on your specific device by using a different dns on your device.

On Android, you should be able to do this by using a normal [google private dns](https://developers.google.com/speed/public-dns/docs/using#android).

Alternatively you can also use an app such as DNS66.

I also sometimes have to do this when I open shopee product share links on my phone.

Do give it a try and let me know the outcome.

**Comment by ragibkl** [comment]
@RAiNYRENJi , when the sites' anti-adblock gets triggered by bancuh-dns, can you check the bancuh-dns logs and see what are the domain names that were blocked? If it's a very small or just a single domain, maybe we can consider whitelisting it ourselves.

The current adblock list configs has been well optimized by @Tomatoide . I usually defer to him if we want to change the lists. But it might be fine to just whitelist 1-2 domains as long as we don't make more ads visible for other users.

**Comment by phanluchoacom** [comment]
You said enforces SafeSearch but Youtube comments is unblocked --> it cannot do because by default safesearch on Youtube it auto hide comments and hide all videos that contains not good for kids or nsfw

**Comment by ragibkl** [comment]
@RAiNYRENJi , I see 2 domains blocked on that. But they look like actual ad domains, so I think we should not whitelist them for now.

Regarding your other listed suggestions with Hagezi lists, I think @Tomatoide had looked at them earlier, and we are using some lists from them already. I think we are fine in that angle as well.

**Comment by ragibkl** [comment]
@RAiNYRENJi , What I mean is, initially I thought there are custom ad domains on that list that we can whitelist, so those sites can work for you. However, I think this is not a good idea. If we whitelist them, it will make the ads show up on other websites as well.

I think, let's not change any blacklist/whitelist configuration for now. When you need to browse those apk download sites, please use the workarounds that I've mentioned here: https://github.com/ragibkl/adblock-dns-server/issues/208#issuecomment-2063565145

Also, your suggestions about using hagezi lists is fine, but I think @Tomatoide have already included them in the current list. Let's not change anything yet.

I'll close this issue ticket since I think this don't need any fixes, and the workarounds mentioned should just work.

Thanks all for you contribution!
Also, sorry for the late reply, I got busy with work.
