### ISSUE TITLE
On ensuring the database's relevance

### ISSUE THREAD

**Issue by babanga** [ragibkl/adblock-dns-server#209]
Was borrowing the domains for the hosts file and noticed that rlwpx_trackers.hosts contains the domain zona.media, an active news media outlet or s0.wp.com (wp's cdn). There are also some legit sites under rlwpx_misc.hosts.

**Comment by ragibkl** [comment]
Hi @babanga , what did you need changed? I'm confused.

**Comment by babanga** [comment]
Hey! Some lists undeer the blacklist directory confused me. I merged them and noticed that some domains are pretty legit, like "zona.media" or "s0.wp.com". I'll stick with rlwpx_advertising.hosts for now

**Comment by ragibkl** [comment]
I see. That list is pretty old. I can't even remember where I sourced them 4 years ago!
Thanks for the feedback!
