### ISSUE TITLE
Logs on fr2 not working

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#210]
Hi @ragibkl it seems logs on fr2 are not working can you check it out thank you

**Comment by ragibkl** [comment]
Hi @Tomatoide , thanks for the report.

I think fr2 ran out of disk space. I took down the services, spin it back up, and now it's fine again.

I suspect that the logs are not being cleared at the 10 mins interval as I had hoped, so maybe this is a bigger problem.

**Comment by ragibkl** [comment]
@Tomatoide , I've reworked the logs module here: https://github.com/ragibkl/dnsdist-acme/compare/065a430c1156ca50490878d87a111fa3d1c9f3bb...master

Also added table borders.

Deployed to fr1 and fr2. Please check them out and see if that actually works better.

**Comment by ragibkl** [comment]
Hi @Tomatoide , I've added the logs endpoint to the status page. https://status.bancuh.com/

Looks like there were some issues still. I've made some fixes to the logs endpoint. Let's see if this will fix it permanently.

The issue was related to how the logs file was consumed.
