### ISSUE TITLE
Some file hosts you need to block in your hosts

### ISSUE THREAD

**Issue by phanluchoa** [ragibkl/adblock-dns-server#22]
Hello,

Today I create this to want you to add more website to the list of block websites. Because I see a lot of website not suitable for everyone to access, such as: porn, gambing, malware,.....
Here I have some link hosts about the website that you need to add to your hosts file in servers:

1:  https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts

2:  https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

3:   https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

Thats all, the site in number 3 its the list of all porn website you need to block. Number 1 and 2 are gambling, malware website you need to block them. Thanks you and have a nice dayy !!!

**Comment by ragibkl** [comment]
Hi @phanluchoa ,

Thanks for the suggestion.
I am already using `StevenBlack gambling-porn`. This should already include items no `2` and `3` in your suggestion.

I will replace this with `StevenBlack fakenews-gambling-porn` instead and it should cover your suggestion no `1` as well.

Please look at my blacklist sources here: https://github.com/ragibkl/adblock-dns-server/blob/master/compiler/data/blacklist-src-urls.txt
If you have more suggestions, please let me know.

**Comment by phanluchoa** [comment]
@ragibkl All of my hosts page you add in blacklist resources its apply for 2 dns in website ???

**Comment by phanluchoa** [comment]
@ragibkl Can you add more these to your hosts file, 3 of this its all of the websites you need to block for me now:

1.
https://gitlab.com/Kurobeats/phishing_hosts/-/raw/master/hosts

2.
https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts

3.
https://badmojr.github.io/1Hosts/Pro/hosts.txt

This its that all for me now. When you add 3 of them to your hosts file you can closed my issues now !! Thanks you and have a nice day !!

**Comment by ragibkl** [comment]
> @ragibkl All of my hosts page you add in blacklist resources its apply for 2 dns in website ??? And all of the website in hosts file its block when we access to that web ??

Yes. The 2 adblock-dns servers I listed on my website is built using that list as source. Of course, this only works if the laptop/computer/phone is using the 2 adblock-dns servers, or if they use a WiFi router as dns, that ultimately point to the 2 adblock-dns servers.

The changes for StevenBlack, I already applied just now, so you can test it.

The additional 3 lists you added is not yet done. I will update here when that completes.

**Comment by phanluchoa** [comment]
> > @ragibkl All of my hosts page you add in blacklist resources its apply for 2 dns in website ??? And all of the website in hosts file its block when we access to that web ??
> 
> Yes. The 2 adblock-dns servers I listed on my website is built using that list as source. Of course, this only works if the laptop/computer/phone is using the 2 adblock-dns servers, or if they use a WiFi router as dns, that ultimately point to the 2 adblock-dns servers.
> 
> The changes for StevenBlack, I already applied just now, so you can test it.
> 
> The additional 3 lists you added is not yet done. I will update here when that completes.

Oke, when you finish update 3 additional list I have suggest you. I think your 2 DNS its smarter and faster dns that I need use. Can I know how much money you have pay for all of 2 DNS ? You will response me through this issue #22. After that, you can closed my issue now. Thanks you !!!

**Comment by ragibkl** [comment]
Hi @phanluchoa 

I added the 3 additional list. Seems like Clefspeare13/pornhosts has been added before this already. I will close this issue now.

Below is the cost to maintain the dns servers.
I am using servers with 2 GiB RAM. They cost USD10 / server / month.
Because I maintain 2 servers, total is USD20 / month.
