### ISSUE TITLE
Feature: Add ForceSafeSearch for Google and Bing

### ISSUE THREAD

**Issue by phanluchoa** [ragibkl/adblock-dns-server#23]
Hello @ragibkl again,

I'm Hoa, I want to you 1 more. Can you add function "Safe Search on Google, Bing". Because I think when you add 2 of them its make all user find something in Google its more safer because they auto block some content that not suitable for users. When you add that function, you search "Video Sex" in Google they do not show for you all websites that have content not suitable. I think this function its very smart and good. 

Here its the article about how we can add SafeSearch in Google, Bing. You dont need to add safesearch in Youtube because its block some videos in Youtube and its block to reply comments. 

Article:  https://support.opendns.com/hc/en-us/articles/227986807-How-to-Enforcing-Google-SafeSearch-YouTube-and-Bing

Thanks you, @ragibkl

**Comment by ragibkl** [comment]
Hi @phanluchoa ,

Can you add more details or articles on how to do this? Cause I have no idea how to start or what it does.

**Comment by phanluchoa** [comment]
> Hi @phanluchoa ,
> 
> Can you add more details or articles on how to do this? Cause I have no idea how to start or what it does.

I have add article about this

**Comment by phanluchoa** [comment]
> Hi @phanluchoa ,
> 
> Can you add more details or articles on how to do this? Cause I have no idea how to start or what it does.

You dont need to add Safe Search on Youtube. Just Google and Bing

**Comment by phanluchoa** [comment]
@ragibkl Can you add my Facebook ? So I can talk with you easier. My FB: https://www.facebook.com/PhanLucHoa.FPTUniversity

Thanks

**Comment by phanluchoa** [comment]
@ragibkl Hello, do you add 2 safesearch of google and bing to your 2 DNS ??

**Comment by ragibkl** [comment]
@phanluchoa , I tried this but have not managed to get it working just yet.
I will definitely update here once I got it to work.

**Comment by phanluchoa** [comment]
> @phanluchoa , I tried this but have not managed to get it working just yet.
> I will definitely update here once I got it to work.

Oke

**Comment by phanluchoa** [comment]
> @phanluchoa , I tried this but have not managed to get it working just yet.
> I will definitely update here once I got it to work.

Can you try to add safesarch by update to file hosts ?? In the article I have update on my issue its has this

![35965D57-5141-43C9-A5D2-1FBBEA3A041D](https://user-images.githubusercontent.com/60943104/74407925-a9767e80-4e65-11ea-8870-8b4d5435fea4.png)

**Comment by ragibkl** [comment]
I see. At first, I tried doing the redirect using the CNAME as target instead.
Maybe I will try using IP address like this instead.
I'll let you know.

**Comment by phanluchoa** [comment]
> I see. At first, I tried doing the redirect using the CNAME as target instead.
> Maybe I will try using IP address like this instead.
> I'll let you know.

Yes

**Comment by phanluchoa** [comment]
@ragibkl I think the method you redirect using its easier to do. Because I think if you use file hosts to change to IP safesurfer of google and bing its not good and not work ok. Sometimes they does not work, so I think the method redirect using CNAME records its neccessary for now. I think you can do it. 

Have a nice day !!!

**Comment by phanluchoa** [comment]
@ragibkl Hello, Does your DNS work with safesearch feature ??

**Comment by phanluchoa** [comment]
@ragibkl Do you finish adding SafeSearch Feature to your DNS ??

**Comment by ragibkl** [comment]
@phanluchoa , I think I managed to get this working, so far only google safe search is done.
I have a draft change at https://github.com/ragibkl/adblock-dns-server/pull/25.

This is for now deployed to the live servers. Please test them for a few days.
If all is working fine, I'll merge the changes into master.

**Comment by phanluchoa-accounttest** [comment]
> @phanluchoa , I think I managed to get this working, so far only google safe search is done.
> I have a draft change at #25.
> 
> This is for now deployed to the live servers. Please test them for a few days.
> If all is working fine, I'll merge the changes into master.

Does all your dns work with safesearch ???

**Comment by phanluchoa-accounttest** [comment]
@ragibkl Now I check I can't see your DNS its enable safesearch on google now

**Comment by ragibkl** [comment]
@phanluchoa-accounttest 
For now, it should work with both adblock dns servers for google search.
Try to search for some sex movie or something. It shows up safe search on top right.

**Comment by phanluchoa-accounttest** [comment]
Can you also add Youtube SafeSearch ?? I think you add safesearch in youtube its secure for kids when they go to youtube to watch

**Comment by ragibkl** [comment]
I can try to add for youtube.
Can you help me confirm that the google force safe search is working?

**Comment by phanluchoa-accounttest** [comment]
@ragibkl I see safesearch its enable now. Now I think you just add Youtube SafeSearch for now. Dont need Bing. Do you have to pay some money for this change of your dns service ???

**Comment by phanluchoa-accounttest** [comment]
On your comment you said that you deployed to live servers and merge all of changes to master. What does that means ??

**Comment by phanluchoa-accounttest** [comment]
After you add SafeSearch on Youtube, can you update this changes about add safesearch in your dns servers to your blog in blog.bancuh.com ??

**Comment by ragibkl** [comment]
@phanluchoa-accounttest 


> @ragibkl I see safesearch its enable now. Now I think you just add Youtube SafeSearch for now. Dont need Bing. Do you have to pay some money for this change of your dns service ???

My servers cost USD 20 / month (2 servers).
This change has no extra effect on server cost. It just takes time to find the correct configuration.

Why you don't want the change on Bing? I think if we can do for google and youtube, bing is just the same effort.

> @ragibkl On your comment you said that you deployed to live servers and merge all of changes to master. What does that means ??
What it means is, when doing development, we typically work on a separate branch/version. That way if we make a mistake, we can just undo everything to the main version.
So, these new changes I'm making, I'm not 100% confident it works. So I work on separate branch and deploy that to live. If people have tested it to work correctly, I can combine the new changes into the main branch/version.

**Comment by ragibkl** [comment]
> @ragibkl After you add SafeSearch on Youtube, can you update this changes about add safesearch in your dns servers to your blog in blog.bancuh.com ??

Sure, that's a very good suggestion!

**Comment by phanluchoa-accounttest** [comment]
@ragibkl Thats ok, you can add safesearch for all google, bing and youtube. Can I know how long does your dns can be enable safesearch for bing and youtube ??

**Comment by phanluchoa-accounttest** [comment]
I think you can make all of changes in your "master branch/version" because I see now the safesearch on google you have setup its ok

**Comment by phanluchoa-accounttest** [comment]
Does your 2 DNS IPV6 work for this safesearch feature ?

**Comment by phanluchoa-accounttest** [comment]
@ragibkl I see you have make change about add safesearch in bing and youtube in here: https://github.com/ragibkl/adblock-dns-server/tree/overrides/compiler/data/overrides.d

So does all of them work ??

**Comment by ragibkl** [comment]
I don't think I've done anything for ipv6. So I don't know if it will work.

bing and youtube the changes are in, but not yet deployed.

**Comment by phanluchoa-accounttest** [comment]
> I don't think I've done anything for ipv6. So I don't know if it will work.
> 
> bing and youtube the changes are in, but not yet deployed.

@ragibkl So first you update my change to IPV4 DNS first, then if ipv4 work ok, you will configure ipv6 ?? Right ?

**Comment by phanluchoa-accounttest** [comment]
@ragibkl Or I think all users work with ipv4 version its a lot. IPV6 its a new version and some of the network dont support them so I think you change for ipv4 only and ipv6 i think you remove them now. Now we just work for ipv6

**Comment by ragibkl** [comment]
I don't know what is needed for ipv6. Maybe you can create a separate issue ticket for testing ipv6 functionality.

**Comment by phanluchoa-accounttest** [comment]
> I don't know what is needed for ipv6. Maybe you can create a separate issue ticket for testing ipv6 functionality.

@ragibkl I has create a new issue about add safesearch type ipv6 already now

**Comment by phanluchoa-accounttest** [comment]
> I don't know what is needed for ipv6. Maybe you can create a separate issue ticket for testing ipv6 functionality.

After you finish add safesearch in bing and youtube on ipv4 version, you can now closed this issue and go to my new issue to configure ipv6 safesearch

**Comment by phanluchoa** [comment]
@ragibkl Hello, do you finish add safesearch bing and youtube to your DNS Servers ?
