### ISSUE TITLE
Feature: Add SafeSearch type IPV6 in AdBlock DNS Servers

### ISSUE THREAD

**Issue by phanluchoa-accounttest** [ragibkl/adblock-dns-server#26]
Hello,

Here its the article about how to configure safesearch in google, bing and youtube in ipv6 version.

Article:  https://www.leowkahman.com/2017/09/11/enforce-safe-search-on-google-youtube-bing/

Thanks you and have a nice day

**Comment by phanluchoa** [comment]
@ragibkl Does that article I have post to my issue its can help me configure safesearch ipv6 ?

**Comment by phanluchoa** [comment]
@ragibkl At this present, I see your DNS does not work safesearch on Bing and Youtube

**Comment by phanluchoa** [comment]
@ragibkl I see now your DNS its enable safe search for all google, youtube and bing now. Now you just configure safesearch of all of them in ipv6 version

**Comment by phanluchoa** [comment]
@ragibkl Do you finish adding safesearch feature on ipv6 version ??

**Comment by ragibkl** [comment]
Hi @phanluchoa ,

Some testing I've done against the current setup. I am using CNAME record for the SafeSearch overrides. Therefore, I believe that both ipv4 and ipv6 are covered. I took a look at the article you shared and since I've already done this using CNAME, there is nothing else I need to do.
As you can see below, both ipv4 and ipv6 results are returned.
1. google
```bash
nslookup google.com dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
google.com	canonical name = forcesafesearch.google.com.
Name:	forcesafesearch.google.com
Address: 216.239.38.120
Name:	forcesafesearch.google.com
Address: 2001:4860:4802:32::78
```

2. Bing
```bash
nslookup www.bing.com dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
www.bing.com	canonical name = strict.bing.com.
strict.bing.com	canonical name = strict-bing-com.a-0017.a-msedge.net.
strict-bing-com.a-0017.a-msedge.net	canonical name = a-0017.a-msedge.net.
Name:	a-0017.a-msedge.net
Address: 204.79.197.220
```

3. YouTube
```bash
nslookup www.youtube.com dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
www.youtube.com	canonical name = restrictmoderate.youtube.com.
Name:	restrictmoderate.youtube.com
Address: 216.239.38.119
Name:	restrictmoderate.youtube.com
Address: 2001:4860:4802:32::77
```

However, my home network is still using ipv4 address, so I don't have 100% confident this works for ipv6 users. We need to have users with ipv6 address to test this functionality.
@phanluchoa , do you have ipv6 anywhere that you can use to test?

**Comment by ragibkl** [comment]
You can refer to the PR where I used CNAME record. https://github.com/ragibkl/adblock-dns-server/pull/25/files
The only other thing that is missing, is DuckDuckGo Safe Search. I think we can add these, using the example in the article you shared.
```
# DuckDuckGo safe search
cname=duckduckgo.com,safe.duckduckgo.com
cname=www.duckduckgo.com,safe.duckduckgo.com
```

I doubt children are using DuckDuckGo to search for porn. If they do, they're probably old enough. Let me know what you think @phanluchoa .

**Comment by phanluchoa** [comment]
@ragibkl Hello, my network support ipv6 so in this period I test your DNS IPV6 its work for now. On my article they have safesearch in DuckDuckGo, I think if you can do, can you add safesearch both ipv4 and ipv6 version to DuckDuckGo Search Engine.  I think its good and you need to add.

**Comment by phanluchoa** [comment]
@ragibkl You add safesearch feature by using code ? Right ? Does them easy or hard ? I have learn just a little about that and I see its so hard for me. Because they have a lots of structure. I cannot remember all :))

**Comment by phanluchoa** [comment]
Here its my results about testing IPV6 DNS:

![test-ipv6](https://user-images.githubusercontent.com/60943104/74650184-b96ac700-51b3-11ea-9871-eb500e4ad804.PNG)

Thanks you

**Comment by phanluchoa** [comment]
@ragibkl  All of now its success. Can you help me this website to your blacklist ?? Here its the website: https://sexmoi.net

**Comment by ragibkl** [comment]
@phanluchoa , I'll make changes for DuckDuckGo. I'll use CNAME as well so it should work the same.

This project is a combination of programming, server and linux knowledge.

The actual dns software is Bind, which is free and open source and runs on linux. Bind is commonly used as dns servers. Bind configuration can be very difficult, but once it is correct, it will work reliably. I don't need programming for Bind part, just need to read the documents.

Programming is done in Python language. I use Python in the `compiler` part, to download and combine the various list of adblock list. Also I use Python to produce the final combined list as a Bind zone file.

Python is very easy for beginners, and suitable for hobby projects like this. If you want to learn programming, I encourage you to start with Python. It is very easy to learn and understand.

**Comment by phanluchoa** [comment]
@ragibkl  As I see when I test all safesearch in IPV6 DNS . I see they not work with youtube and google safesearch. Bing its work ok

**Comment by ragibkl** [comment]
1. @phanluchoa , can I know what you search for on google and youtube? Let me test it as well.

2. Sure, I'll add `https://sexmoi.net` and `DuckDuckGo`.

**Comment by phanluchoa** [comment]
> @ragibkl As I see when I test all safesearch in IPV6 DNS . I see they not work with youtube and google safesearch. Bing its work ok

When I checked each server, youtube and google did not activate safe search mode. And when I added two at the same time, it worked

**Comment by phanluchoa** [comment]
> 1. @phanluchoa , can I know what you search for on google and youtube? Let me test it as well.
> 2. Sure, I'll add `https://sexmoi.net` and `DuckDuckGo`.

I search for anything, example: News, lesson . They not appear safesearch mode in the top right

**Comment by ragibkl** [comment]
> > @ragibkl As I see when I test all safesearch in IPV6 DNS . I see they not work with youtube and google safesearch. Bing its work ok
> 
> When I checked each server, youtube and google did not activate safe search mode. And when I added two at the same time, it worked

You mean, you need to manually add both dns1 and dns2 servers, for the safe search to work?
I think that maybe your PC/Laptop or your wifi router still keep memory of the original google and youtube dns.

Maybe you try to restart your PC/Laptop or wifi router, so that you get new results.

**Comment by phanluchoa** [comment]
@ragibkl Yes, I have delete my google chrome cache, restart computer and restart my modem wifi. Now I can use safesearch for now and I see they are enabled. Thanks you. Please add DuckDuckGo safesearch, my website I have said in my reply to your blacklist. Then you can closed this issue and update new features in your blog at blog.bancuh.com !!! Thanks you and have a nice day !!!

**Comment by ragibkl** [comment]
`sexmoi.net` and `DuckDuckGo safe search` is done. Closing this issue.
