### ISSUE TITLE
Facebook connexion blocked

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#27]
Bonjour, 

I've just noticed that a filter is blocking the facebook connection, I try to connect with facebook on the soundcloud site and I can't, so I decide to test with my fai's, and it works. I think a filter blocks too many things. I'm going to look in your lists, I saw that another person gave you filters, I'm going to analyze them, I think that's where it comes from, some websites don't work for me anymore like for example playing a streaming video on my favorite team's website. I come back to you to tell you what :)

(Can't see the problem, too many filters for me :/ . )

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque 

Here's what you can do to debug this. Open a website in google chrome.
Right-click on the page, and click `Inspect Element`. Go to `Network` tab.
Reload the page.

Observe for network requests that has error.
You can also filter by `status-code:204`.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

I think for facebook, it is `connect.facebook.net`. I'll try to add this now. hold on.

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque , I made the fix, can you test on your side as well?

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque , do let me know if you still face any issues with this.

**Comment by TechComputerServiceDunkerque** [comment]
It's okay on this side for facebook, but it blocks players.brightcove.net. It's possible to whitelist it, thank you.

**Comment by TechComputerServiceDunkerque** [comment]
It is also impossible to open a file on mega.nz

**Comment by ragibkl** [comment]
Sure I'll add those domains to the whitelist.

A week ago, I swapped this out: `https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts`

for this one: `https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts`

the `ultimate` might be too strict and blocks too many list. I think I'll revert this change as well.

**Comment by ragibkl** [comment]
This is done now, and deployed to live servers. Please test to make sure it works.
After that we can close this issue.

**Comment by TechComputerServiceDunkerque** [comment]
Mega.nz is still blocked

**Comment by TechComputerServiceDunkerque** [comment]
Mega works very badly with Bancuh, now there's an error message...

[url=https://www.noelshack.com/2020-08-3-1582121272-2020-02-19-15-06-02-mega-nz-ea5e381d56d4.jpg][img]https://image.noelshack.com/minis/2020/08/3/1582121272-2020-02-19-15-06-02-mega-nz-ea5e381d56d4.png[/img][/url]

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

It seems that we've been getting more issues, ever since I implemented this task: https://github.com/ragibkl/adblock-dns-server/issues/12

Maybe those lists are too strict. I've had to whitelist several domains already since then.
I'm adding a few more whitelist. Let me know if it is still an issue.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque , do test this out and let me know so I can close this issue.

**Comment by TechComputerServiceDunkerque** [comment]
I see problems on aptoide tv, it's a playstore app. I can't download files. The problem of facebook ads persists on android apps, I can't find a list that blocks. For the moment, I don't see any blocked site. If I come across any sites, I'll let you know. Mega's problem is solved.

**Comment by TechComputerServiceDunkerque** [comment]
If you ever need to translate French into English, go to this site, I speak to you in English thanks to him and the translation is clean compared to google translation: https://www.deepl.com/translator#

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

1. I'm glad we fixed the issue with Mega download.

2. I'm also not sure how we can block facebook ads on android. If you have any ideas in future, please share them at [here](https://github.com/ragibkl/adblock-dns-server/issues/13)

3. Meanwhile, I think I will temporarily undo the work in [here](https://github.com/ragibkl/adblock-dns-server/issues/12)
I think it is too strict. We can review them again later. Maybe after we fix aptoide store. I'll close this issue once I undo that change.

**Comment by ragibkl** [comment]
Closing this for now. Please file a new issue ticket for any new issues.
