### ISSUE TITLE
Create the block page on the Adblock DNS

### ISSUE THREAD

**Issue by phanluchoa** [ragibkl/adblock-dns-server#31]
Hello @ragibkl ,

Can you create the block page with categories ? Thats mean when the users use your DNS and type one address on the searchbox and they will redirect to block page with have what categores does they block. For example, when the user type the sexual website on the search box they will auto redirect to the block page with the categories. Like this video: https://drive.google.com/open?id=1dg5SrhpMIehDB_f70cl5W2NueEwF9XaX

Can you please review and set your dns like that !!

Thanks you !!!

There are some categories: 

![image](https://user-images.githubusercontent.com/60943104/75160309-5b5a5880-574c-11ea-99df-cae6c53d0521.png)

**Comment by phanluchoa-accounttest** [comment]
Hi @ragibkl ,

I think this is the guide to configure that: https://navytitanium.github.io/DNSMasterChef/ . Can you go to them and see are they right ?

**Comment by ragibkl** [comment]
Hi @phanluchoa ,

Overall, I think this is good suggestion.
The part we need to do is the redirect page part. From the video that you share, I think I understand what you want to try.
I can break down the feature as follows:

### redirect to a block page
This part is not too difficult. Right now I redirect to the following:
```
$ curl -I sex.com
HTTP/1.1 204 No Content
```
This is basically an empty page. If we replace this with a simple html page, we can show some Blocked Page to the user.
I'm not very good at html and design, but we can try simple one.

Alternatively, we can also show the following to user instead.
- `HTTP/1.1 404 Not Found`
- `HTTP/1.1 403 Forbidden`

### Redirect files (images and javascript)
If we do this, we need special handling for `.js` and image files like `.gif`, `.png` or `.jpg` etc.
This will take time to do but is not too difficult

### Handling of https
If we do the block page, it will only work for website using `http`.
Block site using `https` will not work. It will show some `https` error.
I think this is the same for OpenDNS as well, you can try using OpenDNS and access a blocked site using `https`.
This is because, to show a https site, we need to have valid https certificate for that site. Only the original website can have this.

### Showing of blocked category
This part is a lot more difficult. Right now the list that I'm building and the sources that I use don't have any category information. I also don't keep this information, so this is more difficult to do.
I also need to build a separate service to give this display this category information.
I think, better we ignore the category part, and just focus on the simple features above.

**Comment by ragibkl** [comment]
Hi @phanluchoa , 
This is off-topic, but from your video, it seems like you are using `Gnome Shell` on Linux.
- Are you using Linux?
- Which distro are you using? Ubuntu? Fedora? something else?

**Comment by phanluchoa** [comment]
@ragibkl Hello,

I use Ubuntu

**Comment by phanluchoa** [comment]
@ragibkl So my suggest you can do ??

**Comment by phanluchoa** [comment]
@ragibkl You can use your original website with have certificate to add sub-domain like block.blog.bancuh.com and redirect your dns to that web. If you dont have categories to add you can skip, but can you configure your dns redirect to block page when users go to any sexual or malware websites. You just configure the block page like OpenDNS but you can skip for the block with categories if you not have. Thanks you !!!

**Comment by ragibkl** [comment]
Hi @phanluchoa , 

Based on my description above. I think I can do it. It will take time, but I will start on it.

I don't think I will redirect to `block.blog.bancuh.com`. If we do that, it will be difficult for other people to use this project and setup their own servers. I think it's faster to just show the original url, but show the blocked page. But this part is small detail, so I will try first see how it works.

I will need to do the special file handling first forjavascript and images
The design of the page, I think we will improve later. So initial version will be very basic.

Yes, let's skip the categories.
We will also skip the `https` part.

**Comment by phanluchoa** [comment]
@ragibkl Yes, its ok. You response me when all of that its finish. Thanks !!!

**Comment by phanluchoa-accounttest** [comment]
@ragibkl Hello,
Do you finish create the block page ? You just create the normal page with background screen or background about your website, and have a word "Access Denied by the administrator network". Just like that !!!

![image](https://user-images.githubusercontent.com/61091988/75551710-5c9ac680-5a67-11ea-9b69-1456e75e5c61.png)

**Comment by phanluchoa-accounttest** [comment]
@ragibkl You can see this page, its will help you to create the block page with categories 

https://github.com/opendns/SampleBlockPages/blob/master/block.html and https://github.com/opendns/SampleBlockPages

This is some categories that OpenDNS use: https://community.opendns.com/domaintagging/categories

https://support.opendns.com/hc/en-us/community/posts/220050047-Sites-In-Multiple-Categories

You can watch the example of block page with categories !!!

**Comment by phanluchoa-accounttest** [comment]
@ragibkl Do you finish create the blockpage ?

**Comment by ragibkl** [comment]
Hi @phanluchoa ,

I have a very basic block page right now in live server.
You can just visit http://dns1.bancuh.com or http://dns2.bancuh.com to see it.
If you configured your dns correctly, visiting a blocked site should display the block page as well.

If you are interested, the code is [here](https://github.com/ragibkl/adblock-dns-server/blob/master/adblock_http/www/blocked.html).

I don't have a design or idea to improve it right now, so it is pretty basic. I took a look at the examples you shared. Those look more suitable for a block page with categories. As I said, my system cannot support categories right now, so our block page should have simpler wording. 

Thanks again for the suggestion to add the block page.

I think you can test the block page, and make sure everything works. Then, we can close this issue.

We can always improve the design in the future.

**Comment by phanluchoa** [comment]
@ragibkl Hello,
As I see, I dont have see all of the websites that you add on your host or some file hosts by the link I have send to you its not automatically redirect to that block page. Just some of the website have redirect to that websites. Also can you block help me this websites ? (vlxx.cc) . I have some file blacklist websites hosts, can you register your account in this website: https://my.nextdns.io . Can you set your DNS like this. You create the account configure dns like that page I have send to you. When the users go to the account page, they can update your DNS of your network to the account page. And configure any security or any secure features through that account page. You can use the tab privacy and you will see some of file hosts. You can also configure block any Top Level Domains Extension like that page on tab Security. Can you configure your DNS like that page ?? Users can choose what they want to block to. I hope you can do like that. Thanks you !!!

**Comment by phanluchoa-accounttest** [comment]
@ragibkl Hi,
Can you make the background of the block page ?

Like this: 

https://support.goguardian.com/hc/en-us/article_attachments/201910429/Screenshot_2015-03-23_18.29.18.png

Or this:

https://aacable.files.wordpress.com/2012/11/1231.jpg

**Comment by ragibkl** [comment]
Hi @phanluchoa , 

> As I see, I dont have see all of the websites that you add on your host or some file hosts by the link I have send to you its not automatically redirect to that block page. Just some of the website have redirect to that websites. 

Please check the following for me.
- `nslookup [domain-name] dns1.bancuh.com` should direct to nullzone. it means that the website is blocked by me. If not, please make a suggestion if the site should be blocked.
- also check on the device, `nslookup [domain-name]` to see if dns is setup correctly
- Can you check if you access via http or https? sometimes browsers will try to open via https. As I mentioned, https will see connection issue. and not the block page.

> Also can you block help me this websites ? (vlxx.cc) .

Ok I will do this. HOLY SHIT!

> I have some file blacklist websites hosts, can you register your account in this website: https://my.nextdns.io . Can you set your DNS like this. You create the account configure dns like that page I have send to you. When the users go to the account page, they can update your DNS of your network to the account page. And configure any security or any secure features through that account page. You can use the tab privacy and you will see some of file hosts. You can also configure block any Top Level Domains Extension like that page on tab Security. Can you configure your DNS like that page ?? Users can choose what they want to block to. I hope you can do like that. Thanks you !!!

I'll be frank and say that this is very difficult to do. I don't think I can do this easily. The original goal of this project, is to create an adblock dns system that anyone can install on their own servers quite simply. That page you showed me, looks like a full-featured product. I have an idea of how it works underneath. It has to be dynamically configurable, and have per-ip config.

At the moment, this kind of feature is beyond what I can do in my spare time. Do not worry, let's look for something smaller that we can improve on.

**Comment by ragibkl** [comment]
> @ragibkl Hi,
> Can you make the background of the block page ?
> 
> Like this:
> 
> https://support.goguardian.com/hc/en-us/article_attachments/201910429/Screenshot_2015-03-23_18.29.18.png
> 
> Or this:
> 
> https://aacable.files.wordpress.com/2012/11/1231.jpg

The blue one looks nice. Maybe we can try something similar. But we need to be careful about this. The design may be subject to copyright.

**Comment by phanluchoa-accounttest** [comment]
Hello @ragibkl ,
Can you use all of the hosts file on the websites my.nextdns.io add to your DNS ?

Here its the lists of hosts file you need to add:

1) https://github.com/AdguardTeam/AdguardSDNSFilter
2) https://github.com/anudeepND/blacklist
3) https://github.com/CHEF-KOCH/NSABlocklist
4) https://forum.xda-developers.com/android/general/badmojr-one-host-file-to-block-t3713360
5) https://www.github.developerdan.com/hosts/
6) https://github.com/bigdargon/hostsVN
7) https://github.com/jdlingyu/ad-wars
8) https://github.com/yous/YousList
9) https://github.com/jerryn70/GoodbyeAds
10) https://logroid.github.io/adaway-hosts

Thanks you !!!

**Comment by phanluchoa** [comment]
Hello @ragibkl ,

Can you configure your DNS fulfill the following requirements: 

![0FE3B28A-E595-4CE7-8971-058298424890](https://user-images.githubusercontent.com/60943104/75993638-5fe0f700-5f2c-11ea-8c5a-5caec3a166a1.jpeg)

I think this its suitable for you to configure it
