### ISSUE TITLE
Microsoft blocked? 

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#33]
Bonjour, 

from now on, it's microsoft and outlook.com's mailbox which is blocked, impossible to connect to it. 

https://login.live.com/login.srf

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

Maybe after some recent changes, some microsoft domain got added into the blacklist in some upstream blacklist.

I've manually added this as a whitelist. I hope it works now.
Please help me test it and report back.

**Comment by TechComputerServiceDunkerque** [comment]
it works again
