### ISSUE TITLE
Add ForceSafeSearch Again on Youtube and DuckDuckGo

### ISSUE THREAD

**Issue by phanluchoa** [ragibkl/adblock-dns-server#35]
Hello @ragibkl ,

Sorry again for this, as I see when you unactivated safesearch on Youtube. I see my sons always go to bad videos on Youtube. Can you help me to add again but change safesearch youtube to restrict.youtube.com , not restrictmoderate.youtube.com . I want to strict filtering. And I check the DuckDuckGo Search Engine now I see the SafeSearch does not enabled. Can you add again DuckDuckGo safesearch to safe.duckduckgo.com again. You can follow this article to add:  https://www.leowkahman.com/2017/09/11/enforce-safe-search-on-google-youtube-bing/

I'm sorry for asking you to add and remove this feature on your DNS server, but I'm sure this is the decision this time around and doesn't change. @ragibkl . So please help me one more and create for me the block page redirect !!!

Thanks you and have nice day

**Comment by ragibkl** [comment]
@phanluchoa ,

I think, safe search for duckduckgo is already active. You can test as follows:
```
$ nslookup duckduckgo.com dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
duckduckgo.com	canonical name = safe.duckduckgo.com.
Name:	safe.duckduckgo.com
Address: 52.77.180.62

$ nslookup www.duckduckgo.com dns1.bancuh.com
Server:		dns1.bancuh.com
Address:	139.59.219.245#53

Non-authoritative answer:
www.duckduckgo.com	canonical name = safe.duckduckgo.com.
Name:	safe.duckduckgo.com
Address: 46.137.218.113
```

As for youtube, last time when I tried with `restrictmoderate.youtube.com`, it was too strict. I could not watch a lot of videos, and comments are also disabled.
If we enable `restrict.youtube.com`, it will be even more strict and more videos cannot be watched. Also comments would be disabled.

I think we should not enable this for youtube. It is not a good user experience.

**Comment by phanluchoa** [comment]
@ragibkl Yes, do you finish create block page ??

**Comment by ragibkl** [comment]
@phanluchoa 

I got a bit busy this week, so haven't got the time to work on the block page just yet.

**Comment by phanluchoa** [comment]
> @phanluchoa
> 
> I got a bit busy this week, so haven't got the time to work on the block page just yet.

Yess

**Comment by phanluchoaofficial** [comment]
@ragibkl Hello,
Can you check my inbox on messenger ??
