### ISSUE TITLE
Site to be unblocked

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#40]
Bonjour;

here is a list of sites that are blocked to unblock: 

https://app.adjust.com
https://vivaldi.ampxdirect.com
https://www.rarlab.com
https://www.journaldunet.com
www.linternaute.com
https://static.ccm2.net
http://awin1.com
https://www.flyme.cn
https://www.commentcamarche.net/forum
https://lesannuaires.com/annuaire-radio.html

Also, there is a problem with the facebook messenger, myself and the people I installed your dns can't receive video messenger calls as audio on android, it sounds good but no audio/video streaming, I didn't test on IOS because I don't have an IPhone. Merci

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

I've added these sites to the whitelist, and deployed to live.

I'm not sure how to fix the messenger video calls yet.

**Comment by ragibkl** [comment]
Let's close this issue, there are several others to look at.

**Comment by ragibkl** [comment]
Seems like this one is resolved already
