### ISSUE TITLE
domain to unblock

### ISSUE THREAD

**Issue by pwrguizmo** [ragibkl/adblock-dns-server#45]
Please may you unblock this domain  ? it's a walmark french like company

leclerdrive.fr

Thx

**Comment by TechComputerServiceDunkerque** [comment]
Hey, je viens de proposer une liste pour mettre à jour tout les problèmes venant du DNS, j'attends une réponse voir si c'est ok pour l'administrateur. Donc s'il accepte, on sera tranquille 😃

**Comment by pwrguizmo** [comment]
Merci Jordan

Le dim. 19 avr. 2020 à 22:56, Jordan Impines <notifications@github.com> a
écrit :

**Comment by ragibkl** [comment]
Hi @pwrguizmo @TechComputerServiceDunkerque ,

A quick check of `leclerdrive.fr` just loads an empty domain parking page. Are you sure it is a legitimate website?

Anyway, it does not seem to be blocked anymore in the current blocklist. I'm fine to add it into whitelist for now.

**Comment by ragibkl** [comment]
I've added this to whitelist, so it should propagate to live servers soon. I think we can close this issue.

**Comment by pwrguizmo** [comment]
Sorry i made a mistake while typing the domain name, it is leclercdrive.fr (with a "c")...
