### ISSUE TITLE
Add custom hosts file

### ISSUE THREAD

**Issue by phanluchoaofficial** [ragibkl/adblock-dns-server#51]
Hello @ragibkl ,

Can you add all hosts file sources on this page to your DNS (If they are already added to your dns you dont need to added) :  https://github.com/AdAway/AdAway/wiki/HostsSources

Thanks!

**Comment by TechComputerServiceDunkerque** [comment]
He's already there.

**Comment by ragibkl** [comment]
@phanluchoaofficial ,

I've been to that site, and most of those are already in my list. The ones that are not added, are not as useful.

I think we can close this issue for now.
