### ISSUE TITLE
Test Server in France

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#52]
- 51.158.99.7
- 2001:bc8:600:1810::1

**Comment by phanluchoaofficial** [comment]
@ragibkl Hello,

Servers on France I think its slower than the servers in Tokyo !!! Here is the results:

Here is nslookup and ping to website:

![aa](https://user-images.githubusercontent.com/63760808/80162140-af72a380-85fc-11ea-99e7-effbe17328ef.PNG)

![bb](https://user-images.githubusercontent.com/63760808/80162148-b1d4fd80-85fc-11ea-808c-d2d544cdbc3e.PNG)

Thanks you !

**Comment by TechComputerServiceDunkerque** [comment]
> * 51.158.99.7
> * 2001:bc8:600:1810::1

Shall I test that, friend, and get back to you?  Which list did you add to the one in France?

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque , this dns server has the same setup as the current ones in Singapore. So the list is the same.

Since you mentioned previously that there are users from France, including yourself using the DNS, I want to test the idea of putting servers closer to most users. I'm just curious if there is difference in performance, and if it's worth the effort.

So, I think you should see similar results to the current DNS setup, but I want to know if they are faster.

**Comment by phanluchoaofficial** [comment]
@TechComputerServiceDunkerque All of the lists on blacklists source !!! Details here: https://github.com/ragibkl/adblock-dns-server/tree/master/data/blacklist.d 
He set the block lists and another part like the old adblock dns he has created before !!!

**Comment by ragibkl** [comment]
> > * 51.158.99.7
> > * 2001:bc8:600:1810::1
> 
> Shall I test that, friend, and get back to you? Which list did you add to the one in France?

Yes, please help me test it. @phanluchoaofficial  is also testing another server I setup in Tokyo.

**Comment by phanluchoaofficial** [comment]
@ragibkl I have ever used your france dns at prmary server now and I see they not fast like tokyo server !

**Comment by TechComputerServiceDunkerque** [comment]
I'm testing on Android at the moment, in ping it's 16ms faster on wifi.  On the 4g at orange 23 ms, it's faster than the original server.  I will test tomorrow on pc.

Why don't you test the new lists I gave you on the French server, so I can make more complete tests to help you block more ads etc. and give you a white list later?  If you're interested of course.

**Comment by ragibkl** [comment]
> Why don't you test by adding the new lists I gave you on the french server, ...

I'm not sure what you mean by new lists. I think I've already included your most recent suggestions from [here](https://github.com/ragibkl/adblock-dns-server/issues/41#issuecomment-615929864) into the [source file](https://github.com/ragibkl/adblock-dns-server/blob/master/data/blacklist-src-urls.json)

All my current DNS servers carry the same setup.

**Comment by TechComputerServiceDunkerque** [comment]
No problem, not easy to understand with English.

**Comment by TechComputerServiceDunkerque** [comment]
Hi, can you unlock the next site for me, thank you. (you'd have to create a post where we can give you sites that are blocked) 

https://rapidgator.net

**Comment by ragibkl** [comment]
> Hi, can you unlock the next site for me, thank you. (you'd have to create a post where we can give you sites that are blocked)
> 
> https://rapidgator.net

Hi, this is done.

I will not undo any of the recent list that you gave me. It seems to be working fine, just need to whitelist some sites.

So, if there are any broken sites, you can just create a new issue ticket as usual.

Therefore, you c

**Comment by TechComputerServiceDunkerque** [comment]
Thanks for the french dns, everybody is happy :)

**Comment by ragibkl** [comment]
I've added this server address to my website [here](https://blog.bancuh.com/adblock-dns/adblock-dns-quickstart/). I think we can close this issue for now.
