### ISSUE TITLE
Test server in Tokyo

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#53]
I want to test the theory that a different DNS location will perform better.

I want to test a server in tokyo. If you have time, please test the following DNS:
- 103.29.68.118
- 2400:8902::f03c:92ff:fe3e:46cd

**Comment by phanluchoaofficial** [comment]
@ragibkl Yuppp, this server I have test is fast for me. But server on France you have ever created its slow for me !!!

**Comment by ragibkl** [comment]
I've added this server address to my website [here](https://blog.bancuh.com/adblock-dns/adblock-dns-quickstart/). I think we can close this issue for now.
