### ISSUE TITLE
List of Hosts file to be added to the DNS

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#56]
Copied from here: https://github.com/ragibkl/adblock-dns-server/issues/41#issuecomment-636165125
```
Hello ragibkl,

this is a host that blocks advertising overlay in the world.

https://someonewhocares.org/hosts/hosts

https://pgl.yoyo.org/as/serverlist.php?hostformat=hosts

I'll let you watch.
```

**Comment by TechComputerServiceDunkerque** [comment]
If I ever find other sources, I'll write them down here without any problem.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

It seems that both of these sources are already included in my blacklist.
- https://someonewhocares.org/hosts/hosts
- https://pgl.yoyo.org/as/serverlist.php?hostformat=hosts

They should just work as usual. You can review my current blacklist sources [here](https://github.com/ragibkl/adblock-dns-server/blob/master/data/blacklist-src-urls.json)

**Comment by TechComputerServiceDunkerque** [comment]
Thanks, I didn't mind

**Comment by TechComputerServiceDunkerque** [comment]
Bonjour, 

just one question, is it possible to know how many ads and domains Bancuh is blocking? It's to get an idea for me to write it on my blog. Thanks

**Comment by TechComputerServiceDunkerque** [comment]
I checked before they were not in the list :)

News Filters: 

https://hblock.molinero.dev/hosts
https://hosts.nfz.moe/full/hosts
https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts
https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts

**Comment by ragibkl** [comment]
> Bonjour,
> 
> just one question, is it possible to know how many ads and domains Bancuh is blocking? It's to get an idea for me to write it on my blog. Thanks

Right now, there is no easy way to check. You need a computer with Docker installed. Then you run the following command to get the info. This is basically to get the number of lines in the blacklist zone file.
```bash
docker pull ragibkl/adblock_dns
docker run --rm -ti --entrypoint=wc ragibkl/adblock_dns -l /etc/bind/blacklist.zone
2118154 /etc/bind/blacklist.zone
```
 
As you can see, the adblock dns is blocking about 2.1 million domains. The number will change every time we make changes to the sources, whitelist, or blacklist.

I think this is the highest number yet. I just checked the memory usage on the France server:
```bash
free -h
                     total        used        free      shared      buff/cache   available
Mem:           1.8G        1.2G        126M         96M        465M        268M
Swap:            0B          0B          0B
```
It is using a lot of memory. But there is still 268M that can be used if needed.

**Comment by ragibkl** [comment]
> I checked before they were not in the list :)
> 
> News Filters:
> 
> https://hblock.molinero.dev/hosts
> https://hosts.nfz.moe/full/hosts
> https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts
> https://raw.githubusercontent.com/jawz101/MobileAdTrackers/master/hosts

I've added the sources just now. Also got the updated numbers:
```
docker run --rm -ti --entrypoint=wc ragibkl/adblock_dns -l /etc/bind/blacklist.zone
2215851 /etc/bind/blacklist.zone
```
2.2 million

I hope the servers don't crash

**Comment by TechComputerServiceDunkerque** [comment]
So far, so good, thanks for the information.  I find Bancuh more complete than some DNS that block less ads 🙂

**Comment by ragibkl** [comment]
Closing this issue, since the request has been addressed. Feel free to open a separate ticket for other requests.
