### ISSUE TITLE
Site to be blocked

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#59]
Please add
```
whataporn.tv
www.whataporn.tv
```
to porn blocklist

Amazing project btw keep it up, thank you.

**Comment by Tomatoide** [comment]
Amazing project btw keep it up

**Comment by ragibkl** [comment]
Hi, sorry for late reply. I got busy these few days.
I pushed the latest change with this included.
Thanks for the suggestion. Keep them coming!

I'm closing this issue now, since the request has been completed. Feel free to open a separate issue.
