### ISSUE TITLE
Snapchat & Tiktok ads are no longer blocked? 

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#60]
Hello, 

how are you doing? 

I just noticed that since a few days, the snapchat and Tiktok ads are back, I don't know if it's a dns bug or a host bug that blocks the ads of these two applications.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque , I'm not sure as well. Maybe some of the recent changes to the adblock dns are causing this. Do you see the ads when using the apps on android? or when using in a web browser on desktop?

If we can find the specific ads domains, I'm happy to add them to the current blocklist.

**Comment by TechComputerServiceDunkerque** [comment]
I see the ads on android![S01016-00492210.jpg](https://user-images.githubusercontent.com/42807552/96194061-da093d80-0f49-11eb-9160-718681fa5899.jpg)

**Comment by TechComputerServiceDunkerque** [comment]
I found this

https://www.github.com/d43m0nhLInt3r/socialblocklists/tree/master/Snapchat%2Fsnapchatblocklist.txt 

euw.adserver.snapads.com 23

app-analytics.snapchat.com 9

mqtt-mini.facebook.com

**Comment by ragibkl** [comment]
Okay, I'm adding these for now.
```
127.0.0.1 app-analytics.snapchat.com
127.0.0.1 ase.adserver.snapads.com
127.0.0.1 euw.adserver.snapads.com
127.0.0.1 usc.adserver.snapads.com
127.0.0.1 use.adserver.snapads.com
```
Let's see if it works.

**Comment by TechComputerServiceDunkerque** [comment]
That doesn't work either...

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

I notice that many hosts don't work properly anymore, the ads are more and more present. I will help you to test several hosts to block them and make a new list in a new ticket.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

Is this fixed already? If so please close it.

**Comment by TechComputerServiceDunkerque** [comment]
For snap and Tiktok, I still haven't found the solution

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

The current logs viewer that I'm experimenting with, shows only domains that were blocked.
I'm considering to add logs for domains that were allowed as well. As before it will show logs only for the current user's ip address.

I think it will help with debugging this. But I'm worried about users' privacy.

I only keep small amount of logs, but still it is a risk.

Let me know what you think.

**Comment by TechComputerServiceDunkerque** [comment]
I fully understand that privacy is of great concern. So I contacted blokada to see if he had a solution.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

if you want to block snap ads again, you have to blacklist: europe-west1-gcp.api.snapchat.com

Thanks again for the help
