### ISSUE TITLE
News Hosts

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#61]
Hello, 

here are new lists for your dns 

https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final-Dual.hosts

https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts

https://gitlab.com/intr0/iVOID.GitLab.io/raw/master/iVOID.hosts

https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt

**Comment by ragibkl** [comment]
Added this in the latest commit. https://github.com/ragibkl/adblock-dns-server/commit/b24bc10938834c33c43ce7def6ae67f40cb52456

Should be up and running in live servers in 30 minutes.

**Comment by TechComputerServiceDunkerque** [comment]
Thank you, but paypal does not work very well. Possible to put it in white list

**Comment by TechComputerServiceDunkerque** [comment]
It's okay with me. Thank you

**Comment by TechComputerServiceDunkerque** [comment]
Hello, I have a little problem with messenger and facebook. It's impossible to publish or send a message on android.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

I'm experimenting with a technique to help us debug your issue.

I've added a logs viewer to the dns server. Please visit this site: http://fr-dns1.bancuh.com:8080/
It will check your ip address, and show you dns logs based on your current ip address.

So, put your mobile phone on the dns, and use a web browser on the same mobile to view the logs.

Example of my logs:
`http://fr-dns1.bancuh.com:8080/`
```
ip = 2001:e68:409f:571b:2a7f:cfff:feab:ae00

01-Nov-2020 13:52:53.160 rpz: info: client @0x55962c5effa8 2001:e68:409f:571b:2a7f:cfff:feab:ae00#37314 (zedo.com): rpz QNAME Local-Data rewrite zedo.com/A/IN via zedo.com.blacklist
```

From there, you can look at the logs, and we can hopefully find which domains are being blocked for you, related to messenger and facebook.

Do let me know your findings.

Alternatively, you can paste your logs here, but I don't like that option much, since your logs are your privacy.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

If the link doesn't work, you can try the server's ip as well.
for the france server:
- `http://51.158.99.7:8080`
- `http://[2001:bc8:600:1810::1]:8080`

Other servers follow the same list here: https://blog.bancuh.com/adblock-dns/

**Comment by TechComputerServiceDunkerque** [comment]
I think we need to unlock mqtt-mini.facebook.com & beacons.gcp.gvt2.com

**Comment by TechComputerServiceDunkerque** [comment]
I also checked all the lists of your DNS server, those lists are not updated anymore. You can delete them. 

https://raw.githubusercontent.com/EnergizedProtection/block/master/porn/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://mirror1.malwaredomains.com/files/justdomains
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://justdomains.github.io/blocklists/lists/easylist-justdomains.txt
https://justdomains.github.io/blocklists/lists/easyprivacy-justdomains.txt
https://justdomains.github.io/blocklists/lists/adguarddns-justdomains.txt
https://justdomains.github.io/blocklists/lists/nocoin-justdomains.txt
https://raw.githubusercontent.com/Goooler/1024_hosts/master/hosts

I will send you new lists very soon

**Comment by TechComputerServiceDunkerque** [comment]
News List: 
https://block.energized.pro/unified/formats/hosts.txt (1200K+ Domains blocked)
https://block.energized.pro/extensions/regional/formats/hosts-ipv6.txt (50K+ Domains blocked)
https://block.energized.pro/extensions/ips/formats/list.txt  (50K+ IPs blocked)
https://block.energized.pro/porn/formats/hosts.txt (530K+ Domains blocked)
https://blokada.org/blocklists/ddgtrackerradar/standard/hosts.txt
http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileSpyware.txt
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardApps.txt
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/EasyPrivacySpecific.txt
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/EasyPrivacy3rdParty.txt
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

**Comment by ragibkl** [comment]
> I have identified the error, normally it is enough to whitelist these two addresses.
> 
> **mqtt-mini.facebook.com & beacons.gcp.gvt2.com**

I've added these to the whitelist.

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque 

I've also updated the blacklist sources as per your suggestion. The outdated lists were removed, and new one you suggested were added.

I hope it works better this time.

As always, do report back if anything is broken.

**Comment by TechComputerServiceDunkerque** [comment]
Thanks for the fast work, I hope you now have many users now sir Bancuh DNS ✌️

**Comment by TechComputerServiceDunkerque** [comment]
travaux.ovh.net
ovh.net
ovh.com

**Comment by ragibkl** [comment]
> travaux.ovh.net
> aliexpress.com
> 
> To be unlocked. Merci

Hi @TechComputerServiceDunkerque ,
I've added these sites to the whitelist. I think they should work now.

**Comment by TechComputerServiceDunkerque** [comment]
m.fr.aliexpress.com
fr.aliexpress.com

Ali express france is still blocked.

**Comment by ragibkl** [comment]
> whitelist
> 
> m.fr.aliexpress.com
> fr.aliexpress.com
> 
> Ali express france is still blocked.
> 
> Microsoft:
> 
> watson.telemetry.microsoft.com
> microsoft.com
> settings-win.data.microsoft.com
> 
> Facebook
> 
> usa.ime.cootek.com

Hi, I added these yesterday. I hope it works.

**Comment by TechComputerServiceDunkerque** [comment]
i just checked on the link you gave me to see what the dns blocked on my ip. when i go on aliexpress, the dns tells me that ali express is blocked.

**Comment by ragibkl** [comment]
> i just checked on the link you gave me to see what the dns blocked on my ip. when i go on aliexpress, the dns tells me that ali express is blocked.

Hmm, that should not happen, since we already whitelist aliexpress.
Can you be more specific with the domain name? Or paste the logs here? Is it a slightly different subdomain?

**Comment by TechComputerServiceDunkerque** [comment]
16-Nov-2020 20:42:41.708 rpz: info: client @0x563af8924b28 93.23.127.149#32446 (m.fr.aliexpress.com): rpz QNAME Local-Data rewrite m.fr.aliexpress.com/A/IN via m.fr.aliexpress.com.blacklist 16-Nov-2020 20:42:44.335 rpz: info: client @0x563af8924b28 93.23.127.149#13423 (m.fr.aliexpress.com): rpz QNAME Local-Data rewrite m.fr.aliexpress.com/A/IN via m.fr.aliexpress.com.blacklist

**Comment by TechComputerServiceDunkerque** [comment]
Site à debloquer: go.microsoft. com

**Comment by TechComputerServiceDunkerque** [comment]
Hello, is it normal that google ads are back? Do you need a new filter to block them?

**Comment by ragibkl** [comment]
> https://secure.indeed.com/account/login
> go.microsoft. com
> Paypal.com

Sorry for the slow update. I got busy with work. I've added them to whitelist

> Hello, is it normal that google ads are back? Do you need a new filter to block them?

No, that's not normal. Do you know if there is a specific domain I should add?
 
> I've also just noticed that a filter blocks the servers of the store from apple now mac os and iphon ...

If apple servers are being blocked, I think you can find the domains from the logs-view that we have. Please try to find them so I can add them to whitelist.

**Comment by ragibkl** [comment]
> I've also just noticed that a filter blocks the servers of the store from apple now mac os and iphon ...

Actually, I've had similar experience with software updates for xiaomi android os. So maybe it is something similar.

**Comment by TechComputerServiceDunkerque** [comment]
I'm going to try to watch this, but can you watch if you can connect to indeed, I still can't do it. For Google, snapchat & tiktok, I'm looking for a solution too.

**Comment by TechComputerServiceDunkerque** [comment]
To block snapchat ads, you need to block the following addresses:

us-east1-aws-api.snapchat.com
euw-adsserver.snapads.com
gtq6.sct.sc-prod.net

**Comment by ragibkl** [comment]
> I'm going to try to watch this, but can you watch if you can connect to indeed, I still can't do it. For Google, snapchat & tiktok, I'm looking for a solution too.

I just noticed that the dns in France could not update itself automatically. Some kind of insufficient memory issue. That's why you were having issues with indeed, since the server did not pick up the new updates.

I'll have to sort that out soon.

**Comment by TechComputerServiceDunkerque** [comment]
Thank you, it's really nice

**Comment by ragibkl** [comment]
I'm closing this issue for now, since most concerns have been address. Let's create additional issue tickets if we have more bugs.
