### ISSUE TITLE
twitter media could not be played

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#64]
mobile.twitter.com
media errors out with message 'media could not be played', but works when changing to another dns

**Comment by ragibkl** [comment]
I assume you are using the France server.

Please try it again. Then try to visit the following:
```
http://fr-dns1.bancuh.com:8080/
http://[2001:bc8:600:705::1]:8080/
http://51.158.99.7:8080/
```

It should show you some logs of blocked domains. See if there is any specific domains of twitter that we should whitelist to fix it.

**Comment by Tomatoide** [comment]
seems to be video.twimg.com

**Comment by ragibkl** [comment]
Ok, I've added that to whitelist. Let's hope it works.

**Comment by Tomatoide** [comment]
it works now, thank you
