### ISSUE TITLE
whitelist video.twimg.com [broken]

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#68]
> for some reason video.twimg.com is blocked again as of today, any recent changes? @ragibkl

```
video.twimg.com	canonical name = cs296.wpc.edgecastcdn.net.
cs296.wpc.edgecastcdn.net	canonical name = cs2-wpc.apr-8315.edgecastdns.net.
cs2-wpc.apr-8315.edgecastdns.net	canonical name = cs2-wpc-as.8315.ecdns.net.
cs2-wpc-as.8315.ecdns.net	canonical name = cs531.wpc.edgecastcdn.net.
cs531.wpc.edgecastcdn.net	canonical name = null.null-zone.null.
```

It seems that at the end of this dns query chain, it points to a edge cdn site that has been blocked. I'll need to whitelist them as well.

**Comment by Tomatoide** [comment]
cs531.wpc.edgecastcdn.net is blocked in this list
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt

**Comment by ragibkl** [comment]
Hi @Tomatoide .

I've merged in your changes a couple of days back: https://github.com/ragibkl/adblock-dns-server/pull/73
It should have been deployed already and should have worked.

In any case, I've also added some crude pattern matching whitelist filtering logic as well: https://github.com/ragibkl/adblock-dns-server/pull/75

With that, I've also added some regex rules here: https://github.com/ragibkl/adblock-dns-server/commit/b75f26e3b135d8a27967d16b44f9367cb5c45648

I think, it should whitelist the CDNs properly, and this should just work now.

I'll close this ticket for now. If the issue persists, please re-open this ticket or just create a new one.
