### ISSUE TITLE
Problem with facebook

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#7]
Hello, 

I have a problem with Bancuh DNS on my phone, facebook comments no longer appear or sometimes facebook tells me network error when I am on your dns. I think it comes from the Api Facebook.

Screen: https://image.noelshack.com/fichiers/2019/35/2/1566865932-s90827-02303810.jpg

Screen: https://image.noelshack.com/fichiers/2019/35/2/1566865936-s90827-02305699.jpg

Merci

**Comment by ragibkl** [comment]
Hi @Dadan59DK , Sorry for late reply.

Did you encounter this on the Facebook Mobile App? How about opening Facebook on mobile web browser, same issue? Also, are you on Android or iOS? How did you apply the dns on the phone? Using an app or just change in your home wifi router?

I think some of the recent changes might have blocked some facebook api. I don't know which one I have to whitelist just yet.

**Comment by Dadan59DK** [comment]
Hello, 

I had some problems on facebook on pc, sometimes the page gets blocked with a security error.

On Android, it's worse, I can't do any more research or look at my fan pages.

 I installed your dns on the router of my internet tv box. 

And on Android, your dns is my main server thanks to the Blokada application.

**Comment by Dadan59DK** [comment]
Here is what you need to put on the white list:

https://i.goopics.net/pJeyP.jpg

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

thanks everything seems to work fine, I'll come back to you if I see any problems. I will add your DNS to my blog in the best DNS of the moment, my customers often look at my adblock DNS ranking.

**Comment by ragibkl** [comment]
@TechComputerServiceDunkerque , Thsnks for the fast reply. I'll mark this issue as resolved. I'm glad I could be helpful.
