### ISSUE TITLE
Problems on server Singapore (dns2.bancuh.com)

### ISSUE THREAD

**Issue by phanluchoaofficial1** [ragibkl/adblock-dns-server#70]
Hello,

My name its Hoa again, now I create this to notice you about your DNS dns2.bancuh.com (139.59.218.207) is died now and I can't surf the Internet when using this DNS. Here is result when I try nslookup some of website:

![image](https://user-images.githubusercontent.com/76247252/102686964-ffeae100-421d-11eb-8ec3-e1666c507b42.png)

You can now see the error and I hope you will fixed soon!

Thanks!

**Comment by ragibkl** [comment]
Hi @phanluchoaofficial1 ,

I'm not sure why it happens. Docker service on the server had an issue. I went in and restarted the service. Should be working fine now.

Please check on your side and close the issue if all is good.

**Comment by phanluchoaofficial1** [comment]
They all work now! Thanks!
