### ISSUE TITLE
windows update issues

### ISSUE THREAD

**Issue by Tomatoide** [ragibkl/adblock-dns-server#77]
seems to be related to these blocked:
3.tlu.dl.delivery.mp.microsoft.com.c.footprint.net
cs11.wpc.v0cdn.net
au.download.windowsupdate.com.c.footprint.net

**Comment by ragibkl** [comment]
```
3.tlu.dl.delivery.mp.microsoft.com.c.footprint.net
cs11.wpc.v0cdn.net
au.download.windowsupdate.com.c.footprint.net
```
Ok, I've added the whitelist for now. Let's hope it works.

**Comment by Tomatoide** [comment]
looks like it's fixed now, thank you 👍
