### ISSUE TITLE
Request to add 3 new filters to your Bancuh DNS

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#8]
Hello, 

it's me again, could you add these filters in your DNS server, I finally found the right filters to eradicate ads from android phones (especially facebook), on top of that, these filters are optimized for several countries. 

I hope you will be satisfied with this. 

With kind regards, 

Jordan from TechComputer Service

AdGuard French Filter Optimized: https://filters.adtidy.org/extension/chromium/filters/16_optimized.txt

Blocking ads (standard)
https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt

Antiadblockkiller
https://raw.githubusercontent.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

New DNS ranking on my blog: 

https://techcomputerservices.blogspot.com/2019/06/dns-adblock-list-update-juin-2019.html

Look who's first, thank you for working with you, everyone is satisfied with your DNS.

**Comment by TechComputerServiceDunkerque** [comment]
I also just noticed that the dns blocks Microsoft servers, I can't update my xbox and windows.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

I finally got time to look at this. Sorry for the delay. Regarding the list you provided, I cannot use them in my dns filters. They are probably meant to be used by specific browser adblock extensions or tools. They are not compatible with the scripts I have prepared.

In general, files that I can use with my scripts are called hosts files. Their content should look like this:
`sample.hosts`
```
# additional adservers
127.0.0.1 ad.ettoday.net
127.0.0.1 api.zhy333.com
127.0.0.1 ssh.mi61l.cn
127.0.0.1 www.ailiyou1999.com
127.0.0.1 ailiyou1999.com
127.0.0.1 adservice.google.fr
```

I am glad that you and others find my dns servers helpful. Keep the feedback coming and we can make them better.

With regard to the problem with microsoft servers, we have several options.
1. If you remember, we added the following extra list to my sources
```
https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/rpz.blacklist
```
I think that at least one of them is too strict. We need to vet them and maybe remove the ones that are too strict

2. We can try to find out which domains are used for microsoft servers, and try to whitelist them.

**Comment by ragibkl** [comment]
Temporarily, I've disabled the following list:
```
https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/rpz.blacklist
```
I think it is too strict. Please test the dns servers for a few days, and let me know the result.
- Is windows and xbox update working again?
- Are there too many ads now?

We can find other filter lists to add if it helps.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 
I re-added the following:
```
https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/rpz.blacklist
```
Reason: it was crucial for blocking ads for user. Thanks for testing and feedback.

I found a FAQ section on a related project called PiHole [here](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212/1).

Basically, it lists a list of common domains that they recommend to whitelist. It includes important domains for x-box and windows update.

I hope that fixes your issues with windows and xbox update. Please test them again.

Thanks.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque , let me know how testing goes.

Thanks.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

everything now works for Microsoft servers. thank you
