### ISSUE TITLE
Problem with websites

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [ragibkl/adblock-dns-server#9]
Hello, 

since I install your DNS on my family's routers, everyone is satisfied with the blocker that blocks 99.9% of ads and popup, but I have some problems on websites. 

I'll give you one already, others will arrive, don't close the ticket, thank you. 

http://www.reverso.net/orthographe/correcteur-francais/ (The site does not load correctly)

Here is an extra filter, be careful I think it blocks some facebook functions: see ticket to put them back in white list: https://sebsauvage.net/hosts/hosts

Ticket Whitelist: https://github.com/ragibkl/adblock-dns-server/issues/7. 

Merci

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

1. For the site having problem, I have added the host `cdn.reverso.net` into my whitelist. This should fix the issue.
2. I added the extra filter as you suggested. The whitelist you suggested for Facebook earlier still applies, so don't worry about that. In fact, I have a couple extra whitelist for Facebook.

Do help me test it, and report back any issues.

As always, thank you very much for helping me improve the service. Your feedback is much appreciated.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

if I can help, no problem. If you wish, I can translate your site into French so that it can be developed in France, if that interests you of course.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

I have customers who have problems with Total 360 Security antivirus, the antivirus does not update with Bancuh DNS. Can you whitelist their servers? However, I don't know the antivirus's server addresses. The site https://www.360totalsecurity.com/fr/ is also filtered. Thank you.

**Comment by ragibkl** [comment]
Hi,
I'll start making the fixes. But might be delayed a bit. Will update here soon.

**Comment by TechComputerServiceDunkerque** [comment]
Merci 🙂

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

I added the above sites to my whitelist. However I did not do any detailed testing. So, for now test them yourself, and get back to me after a few days.

If you have any other legitimate sites that are broken, do list them down.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

Thank you, I just discovered 3 new hosts files for your dns, I'm testing with blokada and I see that these 3 filters block facebook audience network ads correctly when they are together, I've been testing under Android for almost 1 hour and no ads appear, here are the 3 lists to add: 

#1 - https://getadhell.com/standard-package.txt

#2 - https://pgl.yoyo.org/as/serverlist.php

#3 - https://hosts-file.net/ad_servers.txt

Site that are to be unlocked: 

- https://www.01net.com/
- https://best.aliexpress.com/
- https://www.doctissimo.fr/

The problem continues on the 360 security site, the page does not load completely.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

I think I managed to fix the 360 security site. Please check again when you have time.
I added the sites you listed to my whitelist as well.

With regard to the adblock lists:

#1 - https://getadhell.com/standard-package.txt
- This one have not been added. I'll test it a bit more, and make a deployment soon.

#2 - https://pgl.yoyo.org/as/serverlist.php
#3 - https://hosts-file.net/ad_servers.txt
Both 2 and 3 are already included on my blacklist, so we don't have to do anything here.

Sorry for late reply. My work got a bit busy past 2 weeks, and I did not have time to catch up with this.

I'll keep this issue open until I can apply that one blacklist, and until you can confirm all working.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

Thank you for the answer, https://www.01net.com/ still doesn't work. If I ever have other lists with new blockages, I will send them to you. I also wanted to know, are you blocking fraudulent sites? Because I have several who annoy some customers?

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

I think I missed another domain for www.01net.com. I made the fix. I hope it works now.

I also added `https://getadhell.com/standard-package.txt`. I hope nothing breaks. We are blocking about 1.4 million sites now.

You can take a look at my block list [here](https://github.com/ragibkl/adblock-dns-server/blob/master/compiler/data/blacklist-src-urls.txt).
Basically, I use several upstream sources, and they block the following kind of sites:
- ads
- user tracking servers
- porn sites
- adware/malware, sites that may harm user's computer

I'm not sure what you mean by fraudulent sites. I don't like to block too much content, cause I think if users don't like what they see, they just browse somewhere else.

Maybe you can share more details what you mean by `fraudulent sites`?

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

for example, sites that open with popups, in France there are many that are not blocked by Bancuh, also there are some porn sites that are not blocked by your list. 

01.Net now works, thank you.

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

I think, the issue here is that perhaps some French websites are not in my block list. So if we want to improve this, I need to find some french adblock list to add to mine.

I found one here: `https://easylist-downloads.adblockplus.org/liste_fr.txt`
but it is not in hosts format. I will try to extract some of the domains, so we'll see how it goes.

We can also try to start our own list. But it might be a slow process.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

here is a list already ready, I don't know if this is the one you already have:

https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/127.0.0.1/hosts
http://sbc.io/hosts/alternates/gambling-porn/hosts

If I find other sources, I'll send them to you

**Comment by TechComputerServiceDunkerque** [comment]
on the other hand, I have two websites that are blocked: 

- https://mywot.comhttps://dl.clubic.com
- https://dl.clubic.com

**Comment by TechComputerServiceDunkerque** [comment]
Hello, can you block this site there, it's popups that open every time.

http://reward3952.nonamemonth55.live/3252848611/?utm_campaign=QPF8euu28II5lw7O2iHhCugVqK5RzfdNsTpLaMM91qY1&t=main9_363c72030a6a3b060a66096e2c0c&f=1&fp=%2Fo5FYjqQp1Hs8JGOH2W16cHY2PVF6reW%2FVzc%2BnWWXja5ONFdyb6vocqLG2mnCAM9vrRphZ%2F8dTTKgUz0H8siUyPArMfbsMjbjcgqGMRKGKuA4Os7S1cIKeZeal2E33lbLsOcwLRkLgqN0ja%2BdtZuDfpPxAFpGO77nW9%2F7eJB6eQ%2FLeDZfXQaLyisk1%2BJeMNEn2lpyTlwxN10KVpYJvRKe2bVwUBKwSkSugl4X1YdmZ5gR4oKG%2FWgYvafaxudiqzhgpiSiisMz4XigloiZKyK6EV2ngUp%2F0qqbJDXASxeABCRD83d7dfUKwIhOG4PycbyLtu8BPvZ3lpTFCbVlQvNlx7reikjW7I8l7%2BHtUylj6u5zDieizzKWYMcnEgwVE40Rgr1BupykJU3iqItTpehdGFpSl8nlmUmV6VHPcjSSSWb3JEK%2FrSR9lIbJ2XD8ODWI1cR8%2FWaMIl0OpAawzLNvyxo0qWbxRvtTwweu%2FQrvvG1W4vERQRdqIfNoqNN3HMhbOGPowNludlsaUvR%2B0dzfjGC6ylJC2zIXLOg2rueDDW6WAE%2FzEVPOceqJkiyuSqc9ZOO0%2FcdZlS9UQk2d2bbF6yJmGOUzxiT5TWXSGHOcAzQvwFz8%2FvQYJaEV9nwIGone31NJxP1qQ7WfxOWBSf86KoGTxI%2Bl7L0kW%2FZraNQE1jSlJug4yll0lPpdBb%2B1ftR

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque 

I added the 2 whitelists you gave me.
Also I tried to unblock the 4 websites you mentioned. I tested them roughly, and they seem to work. `dl.clubic.com` does not seem to want to work though.

I am not able to view the popup website that you mention. My browser just won't let me open it, cause it's unsafe. I'm not sure what I can do here. I can probably just block that specific domain. How do users get to them though?

**Comment by TechComputerServiceDunkerque** [comment]
Hello, 

thanks for everything, for dl clubic, it's normal it's a site where you can download legal software, it generates different links. Otherwise for the site I gave you, it's a site that many older people have reported to me, they open with popups and when you go back, it puts other popups on some streaming and download sites.

If I ever have anything else, I'll pass it on to you. Bancuh still doesn't block facebook ads.

**Comment by TechComputerServiceDunkerque** [comment]
I have a big problem with https://outlook.com, I can't read my emails, I can't connect, but the site loads in a loop and nothing comes.

**Comment by TechComputerServiceDunkerque** [comment]
Hello, it is possible to block these pages, they are fraudulent sites: 

- http://176.114.9.149:8081/offer?sid=MixEU_k2&keys=dns+ad+blocker&lan=en&redir=http%3A%2F%2F149.202.65.142%2FmxJV5f%3Fsub_id_1%3DMixEU_k2_tb

- http://hsek.luma-kunst.de/

**Comment by ragibkl** [comment]
Hi @TechComputerServiceDunkerque ,

Sorry for late reply. I haven't had much time to work on this.

That link you showed `http://176.114.9.149:8081` is using ip address. From my knowledge, this type of link will go direct to the server at that ip address, bypassing the dns lookup. Hence, we cannot block this using Adblock DNS.

The hosts file at `http://rlwpx.free.fr/WPFF/hosts.htm`, I think I will test them as well, and maybe include them in my list.

I have not looked at how to properly block Ads on Facebook page just yet.

I this this issue thread is getting too long. This can get very hard to manage. I would like to close this issue. We can open individual github issues for each problem we want to tackle.
