### ISSUE TITLE
Problem showing avatar images when watch videos livestream on Youtube

### ISSUE THREAD

**Issue by phanluchoa21** [ragibkl/adblock-dns-server#90]
Hi,

I have one problem when using your DNS to watch video live on Youtube, I cannot see avatar images on live youtube. I think you have blacklist this domain! You can see images below to see that and after that can you take that website to whitelist ?

![image](https://user-images.githubusercontent.com/78642061/110738995-df518680-8262-11eb-9ead-5abb015c1340.png)

Thanks!

**Comment by ragibkl** [comment]
Hi @phanluchoa21 ,

Thanks for the report! I've added that domain to the whitelist here: https://github.com/ragibkl/adblock-dns-server/commit/0171e64cf7d0083d74019a4d89c04bc45f4dc1e3

Let's hope that it's fixed by this.

**Comment by phanluchoa21** [comment]
> Hi @phanluchoa21 ,
> 
> Thanks for the report! I've added that domain to the whitelist here: [0171e64](https://github.com/ragibkl/adblock-dns-server/commit/0171e64cf7d0083d74019a4d89c04bc45f4dc1e3)
> 
> Let's hope that it's fixed by this.

Okk! It fixed now. Thanks!
