### ISSUE TITLE
export dns logs in a sidecar

### ISSUE THREAD

**Issue by ragibkl** [ragibkl/adblock-dns-server#93]
At the moment, the http-logs-viewer reads the blocked dns requests directly from the logs files.

This creates a tight coupling between these 2 services. In addition, if the dns server restarts, logs are lost completely. Also, it's difficult to display logs to user if we have 2 dns servers in a region.

This is also a blocker for moving into microservice based solutions such as kubernetes.

These 2 operations should be decoupled. 

We need a way to export the logs into a temp storage service like mysql or redis, during runtime of the dns server. Additionally, we can build the http logs viewer to read from the storage, instead of the log files.

**Comment by Tomatoide** [comment]
Do logs work when DoH is activated for you @ragibkl ? It doesnt seem to work for me

**Comment by ragibkl** [comment]
Hi @Tomatoide ,

I tested this just now, and it works fine for me. Usually, it might not work if the dns query and the logs are viewed by different ipv4 vs ipv6. So I usually just disable ipv6 on my laptop to view this consistently.

**Comment by ragibkl** [comment]
I'm closing this issue for now, for the following reasons.

Initially I thought that we needed this so that we can make it easier to debug dns queries on just a single location.

Looks like most people are just happy debugging their dns logs on each server directly.
Logs never leave the server, deleted each 10 mins.
Maybe this is best for user's privacy.

Current focus is to fix the logs endpoint, and maybe integrate front-end logs viewing directly on web-bancuh.
In any case, this is not needed.
